### ISSUE TITLE
What does it mean "the Orphanet classification is polyparental"? What criteria does Orphanet use to assign a preferential parent?

### ISSUE THREAD

**Issue by Michele-N** [OD4RD/Main-Help-Desk#10]
What does it mean "the Orphanet classification is polyparental"? What criteria does Orphanet use to assign a preferential parent?

**Comment by MCecile-US14** [comment]
Dear Michele, Thank you for posting! Remember to assign your issue (right pannel) to someone (me for instance) so I will get a notification to see and answer your post and to flag your issue accordingly (right panel). I let you try and come back to me with any question.

**Comment by MCecile-US14** [comment]
Dear @Michele-N, 

I just added a specific section in the Wiki 'classification' Q/A about preferential parent in Orphanet and how to access this information from the linearisation file, feel free to use it as an official Orphanet answer.
[Preferential parent](https://github.com/OD4RD/Main-Help-Desk/wiki/Orphanet-classification#how-to-find-the-preferential-parent-of-a-rare-disease-in-orphanet-classification-how-to-access-the-information-in-the-linearisation-file).

Kind Regards, 
Marie-Cécile
