### ISSUE TITLE
discrepancy between "Search for intellectual disability-related genes" and search for a rare disease

### ISSUE THREAD

**Issue by MichaelaFux** [OD4RD/Main-Help-Desk#100]
Searching for the gene KMT2E in intelectual disability-related genes results in ORPHA 528084: https://id-genes.orphanet.app/ithaca/

When serching for that ORPHA code the OMIM number for KMT2E, which is 608444, is missing: https://www.orpha.net/consor4.01/www/cgi-bin/Disease_Search.php?lng=EN&data_id=27491&Disease_Disease_Search_diseaseGroup=Non-specific-syndromic-intellectual-disability&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Non-specific-syndromic-intellectual-disability&title=Non-specific%20syndromic%20intellectual%20disability&search=Disease_Search_Simple

Is the OMIM list for ORPHA528084 not up to date or is the information on the gene realtion wrong?

Thank you for your support.

**Comment by OrphanetSwitzerland** [comment]
After discussion with Michaela, the request is adding OMIM number 618512 to ORPHA:528084.

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, Dear @MichaelaFux, 

Thank you for your message. I will check your request to add this OMIM number at the beginning of the next week. If we need to evaluate the creation of a new ORPHAcode, it will be longer but in any case, I will let you know. 

Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, Dear @MichaelaFux, 

I have validated your request to add the OMIM number 618512 to ORPHA:528084 with a relationship BTNT. This will be visible in the next 24h.

Thank you !

Best, 

Julie

**Comment by OrphanetSwitzerland** [comment]
Thanks!
