### ISSUE TITLE
Snijders Blok-Fisher syndrome

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#103]
Hi,

Would it be possible to connect this syndrome - Snijders Blok-Fisher syndrome - to the gene POU3F3?

References:
https://www.omim.org/entry/618604
https://www.ncbi.nlm.nih.gov/medgen/1684801

Best,
Lene
Norway

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

Thank you for your message, I will review this request. At the moment, we have a delay of 2 months. 

Thank you for your patience, 
Best, 

Julie

**Comment by LeneMartinsen** [comment]
Thank you @JTorphanet 
I forgot to add: The request has been in RIC since 2021.
This information was added by Marie-Cecile one month ago:
Hello Emilie,
Could you please take a look at this request and include it in the next disease meetings. It has been pending for a while now, the request is linked to our scientific watch reference list also.
Apparently 'POU class 3 homeobox 3' - POU3F3 gene is already existing in Orphanet (ID#30360) but not linked to any disease

Totally understand that there is a delay. Just wanted to let you know :)

All the best,
Lene

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

The Orphanet committee has validated the creation of this disease with the name: "Intellectual disability-cupped ears syndrome" under ORPHAcode: 656135. We keep the OMIM name as synonym.

Thank you for your patience, 

Julie
