### ISSUE TITLE
Atrophoderma of Pasini and Pierini

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#104]
Hello,

Based on a request from a Swiss coder, please consider the inclusion of the entity Atrophoderma of Pasini and Pierini.

References:
-	https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6389486/
-	https://www.ncbi.nlm.nih.gov/books/NBK519069/

Kind regards

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Can you please provide more details upon each of your request: context of request, patient coding, origin of demand, documentation
And resume the maximum of information you transmitted us (epidemiology, number of cases reported so far, familial history for patient case etc..)
We do dispatch and priotorize creation of ORPHAcodes depending of those details with high priority for patient care; the more precision we received the fastest it can be managed and validated.

Thank you,
Marie-Cécile

**Comment by MCecile-US14** [comment]
Hi @Orphanet-AysegulSenol, 

Can you assess the creation of this disease when you have time?
Thank you, 
Marie-Cécile

**Comment by Orphanet-AysegulSenol** [comment]
Dear @OrphanetSwitzerland,

I will work on this possible creation and keep you posted. In the meantime, any additional information about this entity will be welcomed as Marie-Cécile mentioned.

Best regards, 

Aysegul

**Comment by OrphanetSwitzerland** [comment]
We don't have much information to add.

From the patient’s file:

_The diagnosis is: Multiple sharply demarcated hyperpigmented macules, forearms flexor bilaterally, a.e.Atrophoderma Pasini et Pierini, DD post-inflammatory skin lesions Erythema dyschronicum perstans/status post lichen aureus/actinicus.
Biopsy left forearm: Superficial perivascular hypermelanotic dermatitis with a slightly irregular epidermal band and areal basal melanin-hyperpigmentation, discrete acanthosis and basket-weave orthokeratosis, superficial to discrete lymphohistiocytic infiltrates with isolated plasma cells._

In one report it is stated _"Morphea - Atrophe variant Pasini Pierini” and as additional information “Vitiligo”._

The coder wanders if she could use the ORPHA:90289 - Localized scleroderma (for which Morphea is a keyword). 

From the article Idiopathic Atrophoderma of Pasini and Pierini: Case report and literature review:  “Finally, in 1958, Canizares et al coined the term Atrophoderma of Pasini and Pierini (APP) and identified unique features in comparison to morphea”.

**Comment by Orphanet-AysegulSenol** [comment]
Dear @OrphanetSwitzerland 

Thank you very much for the information. I confirm that I started to work on this demand and I will keep you posted. 

Best regards, 

Aysegul
