### ISSUE TITLE
Rauch-Steindl syndrome (RAUST)

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#105]
Hello,

Based on a request from a Swiss coder, please consider the inclusion of the entity Rauch-Steindl syndrome (RAUST).

References:
-	https://pubmed.ncbi.nlm.nih.gov/36589751/
-	https://omim.org/entry/619695
Kind regards

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Can you please provide more details upon each of your request: context of request, patient coding, origin of demand, documentation (e.g. here specifying where the swiss coder' need comes from)
And resume the maximum of information you transmitted to us: epidemiology, number of cases reported so far, familial history for patient case, is there any other resources for this disease (patient organization etc..)
We do dispatch and priotorize creation of ORPHAcodes depending of those details with high priority for patient care (a missing ORPHAcode is blocking the coding of a patient); the more precisions we received the fastest it can be managed and validated.

Thank you,
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @JTorphanet, 

Can you look up this request in the coming months
Thank you, 
Marie-Cécile

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland,

This creation has been reviewed and the Orphanet committee has validated the creation of the "Rauch-Steindl syndrome". Unfortunately, due to a technical issue affecting the database we are not able to create an ORPHAcode for the time being. I will close the ticket but as soon as the ORPHAcode is created I will post a message to inform you. 

Thank you for your understanding,
I wish you a very happy festive season! 

Julie

**Comment by JTorphanet** [comment]
Creation under ORPHAcode: 659642	

Julie

**Comment by OrphanetSwitzerland** [comment]
Hello, we noticed that the entity was created as a sub-type and there is no disorder-level entity above it. Is it normal? Shouldn't it be classified as a disorder?

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Thank your for your review, indeed I think it was a mistake from the creation of the disease in the database. I just corrected it as a disorder > Malformation syndrome. It will be visible from next week on the website
Kind Regards
Marie-Cécile
