### ISSUE TITLE
Sunflower syndrome

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#106]
Hi!  We had a request from a medical student at Albert Einstein. He and a group of his colleagues are working with patients affected with this syndrome and they want to start a non-profit organization.  After an initial review, I believe that this is a rare condition and would like to ask if this term can be added to the Orphanet rare diseases list. 

Definition: Sunflower syndrome is a rare, epileptic disorder characterized by highly stereotyped seizures. During these seizures, individuals with Sunflower syndrome turn toward a bright light while simultaneously waving one hand in front of their eyes. This unique behavior is coupled with abrupt lapses in consciousness. https://www.massgeneral.org/children/sunflower-syndrome#

"Individuals with Sunflower syndrome often develop eyelid myoclonia, including exhibiting symptoms of eye fluttering and eye rolling, often years before the onset of handwaving episodes. In this way, Sunflower syndrome shares kinship with Jeavons syndrome. There is also a similar age at onset, typically in the first decade of life, both are more common in females, both are generalized epilepsies, and both are often refractory to treatment.  Sunflower syndrome and Jeavons syndrome also have similar interictal and ictal EEG features, including polyspikes and spike-wave complexes. A photoparoxysmal response is also a common feature.In her 1983 report, Ames differentiated her patients with handwaving episodes from those with other photosensitive epilepsies by indicating the former produced EEGs with more frequent runs of spikes and polyspikes, but of shorter duration, when exposed to intermittent photic stimulation. The very stereotyped behavior of patients turning towards a light source and then waving their hand in front of their face may distinguish Sunflower syndrome from Jeavons syndrome. However, given the similarities described above, the relationship between these two syndromes is not yet clear." https://onlinelibrary.wiley.com/doi/10.1111/dmcn.14723

Also, from the "International League Against Epilepsy classification and definition of epilepsy syndromes with onset in childhood:
Position paper by the ILAE Task Force on Nosology and Definitions", in the section about  Epilepsy with eyelid myoclonia
4.1.1  |  Overview
"This syndrome (previously known as Jeavons syndrome) is characterized by the triad of frequent eyelid myoclonia, with or without absences, induced by eye closure and photic stimulation. Eyelid myoclonia is often most prominent on awakening (Table 6).
A subgroup of patients with EEM have prominent photic induction of eyelid myoclonia (with or without absence), and absence or myoclonic seizures.86 This subgroup has previously been referred to as “sunflower syndrome,” due to sun-seeking behavior, as they may turn their faces to the sun as a light source at seizure onset.87 This subgroup can be termed “EEM with prominent photic induction.”  https://www.ilae.org/files/dmfile/onset-in-childhood2.pdf

You list Jeavons syndrome in Orphanet: 
 [(https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=16894&disease=Jeavons-syndrome&search=Disease_Search_Simple)

More relevant articles: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6051521/
https://onlinelibrary.wiley.com/doi/10.1111/dmcn.14723
https://onlinelibrary.wiley.com/doi/10.1111/epi.17683
https://www.epilepsy.com/sites/default/files/2022-10/Epilepsia_2022_fisher_visually_sensitive_seizures.pdf
https://www.epilepsybehavior.com/article/S1525-5050(21)00090-1/pdf

Other articles: 
https://pubmed.ncbi.nlm.nih.gov/37632399/
https://pubmed.ncbi.nlm.nih.gov/36562419/
https://pubmed.ncbi.nlm.nih.gov/34704936/
https://onlinelibrary.wiley.com/doi/10.1111/dmcn.14965
https://pubmed.ncbi.nlm.nih.gov/33639438/
https://pubmed.ncbi.nlm.nih.gov/33070054/
https://pubmed.ncbi.nlm.nih.gov/32554362/
https://www.uptodate.com/contents/photosensitive-epilepsies

See also: https://www.massgeneral.org/children/sunflower-syndrome,  https://www.massgeneral.org/assets/mgh/pdf/neurology/sunflower-syndrome-guide-2022-final.pdf and https://www.massgeneral.org/children/sunflower-syndrome.  There is also a CT: https://clinicaltrials.gov/study/NCT03790137?tab=results

Thank you, Gioconda Alyea

**Comment by MCecile-US14** [comment]
Dear @galyea123, 

Thank you for your request and all the details already provided. 
We will revise this condition for inclusion in the Orphanet Nomenclature in our next disease meeting in November 2023 and keep you update of the decision.

Kind Regards, 
Marie-Cécile Gaillard

**Comment by galyea123** [comment]
Thank you!

**Comment by MCecile-US14** [comment]
Dear @galyea123, 

After evaluation of the creation of the 'Sunflower syndrome' as a distinct entity, Orphanet' scientific and medical committee decided to not create this as an individual clinical entity based on the ILAE classification whom considers Sunflower syndrome as a subgroup of EEM. 
Thus to represent this better, please note we updated Orphanet' nomenclature accordingly regarding ORPHA:139431 renamed 'Epilepsy with eyelid myoclonia' with 'Jeavons syndrome' and 'Sunflower syndrome' as a keyword to facilitate the search.

These change will be visible within 24 hours on the website.

Kind Regards, 
Marie-Cécile

**Comment by galyea123** [comment]
Thank you, because it is a subtype of EEM, and there is enough evidence of it, I thought this can be included.  I will wait to see the changes. Sincerely, Gioconda
