### ISSUE TITLE
Binswanger disease (subcortical vascular dementia)

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#107]
Hi!  The term Binswanger disease was obsoleted.  I would like, if possible, to know the reasons, as it is still largely mentioned in the medical literature, included the NIH: https://www.ninds.nih.gov/health-information/disorders/binswangers-disease.

Thank you!

**Comment by caterina-lucano-orphanet** [comment]
Dear user, thank you for your interest in the Orphanet Nomenclature. Binswanger disease was obsoleted by Orphanet in 2017.

Binswanger disease is a common cause of vascular dementia in the elderly. Criteria for diagnostics include: "Absence of other known causes of white matter disease, Subcortical arteriosclerotic encephalopathy (SAE), small vessel dementia, chronic microvascular leukoencephalopathy". Therefore it is more a pathological process than a disease.

According to the consulted expert, Pr Dominique Hervé, Binswanger disease is a historic definition of a pathological process used for severe presentation of small cerebral artery diseases, of genetic origin or not.  Furthermore, it is likely non rare. 

REFs:
(2000) PMID: 11441570 Binswanger's disease is not a single entity.
(2010) PMID: 20875648 Binswanger disease: An update
(2014) PMID: 25201523 Binswanger's disease: toward a diagnosis agreement and therapeutic approach.
 
I hope this clarifies the issue for you.
Kind regards,

The Orphanet Nomenclature Team

**Comment by galyea123** [comment]
Thank you for your answer.  As commented, there are some recent articles about BD including the NIH and some of these analyze the different aspects of diagnosis and treatment. 
Thanks again! Gioconda Alyea
https://onlinelibrary.wiley.com/doi/10.1002/ccr3.3459
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7766314/
https://www.ninds.nih.gov/health-information/disorders/binswangers-disease
https://pubmed.ncbi.nlm.nih.gov/21239411/
