### ISSUE TITLE
Current number of active disorders and subtypes

### ISSUE THREAD

**Issue by uunter98** [OD4RD/Main-Help-Desk#109]
Dear Marie-Cecile, can you please tell me how many active entities we currently have (in the new nomenclature pack) on disorder and subtype level (EXCLUDING groups of diseases)? I would need the number in order to check whether I filtered the list of 2023 correctly. Thank you and kind regards, Ursula

**Comment by MCecile-US14** [comment]
Dear @uunter98, 

Thank you for your request, please refer to the bi annualy clinical entities numbers table we release here on the Wiki page of the GitHub as reference: https://github.com/OD4RD/Main-Help-Desk/wiki/1.-ORPHAcodes-&-Nomenclature#orphanet-nomenclature-update

Kind Regards, 
Marie-Cécile

**Comment by uunter98** [comment]
Thank you so much, Marie-Cecile! I was not aware of this useful resource (shame on me..)! Ursula
