### ISSUE TITLE
 Collagen VI-Related Dystrophies

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#112]
I am suggesting to add a new term and merge two/three diseases that were listed as separate conditions.  

 Collagen VI-Related Dystrophies (as per GeneReviews): Collagen VI-related dystrophies (COL6-RDs) represent a continuum of overlapping clinical phenotypes with Bethlem muscular dystrophy at the milder end, Ullrich [congenital](https://www.ncbi.nlm.nih.gov/books/n/gene/glossary/def-item/congenital/) muscular dystrophy (UCMD) at the more severe end, and a [phenotype](https://www.ncbi.nlm.nih.gov/books/n/gene/glossary/def-item/phenotype/) in between UCMD and Bethlem muscular dystrophy, referred to as intermediate COL6-RD" (I believe this intermediate phenotype is myosclerosis)

https://www.ncbi.nlm.nih.gov/books/NBK1503/

**Comment by MCecile-US14** [comment]
Dear @Orphanet-AysegulSenol, 

Could you please take a look at this as you are currently revising Bethlem and Ullrich diseases ? Not sure about the new term to be added.

Thank you,
Kind Regards, 
Marie-Cécile

**Comment by Orphanet-AysegulSenol** [comment]
Hello, 

Thank you for sharing your suggestion. As you have also mentioned, « Collagen VI-related dystrophies » presents a spectrum of which Ullrich congenital dystrophy is at the severe end and Bethlem muscular dystrophy (Bethlem myopathy) is at the milder end, and there is an intermediate form between these two conditions. 

Actually following the request of the experts, also currently providing abstracts for Ullrich congenital dystrophy and Bethlem muscular dystrophy, the clinical group of « Collagen VI-related dystrophies » and the entity « Intermediate Collagen VI-related dystrophy » . Detailed information will be available in Orphanet website as soon as the abstracts are published but meanwhile if you need further information please let me know. 

Concerning the « Myosclerosis », it is a different entity (Orpha : 289380) classified under « Non-dystrophic myopathy whereas « Collagen VI-related dystrophies » thus also the intermediate form, are part of « Muscular dystrophies ». The common point is they share Collagen-6 mutations but Myosclerosis has significantly different clinical features (you can consult the definition provided in Orphanet website). 

I hope I addressed all the points you have raised but if not please do not hesitate to contact me. 

Best wishes, 

Aysegul

**Comment by galyea123** [comment]
Thank you!  I look forward for the updates. 
Warm regards!
Gioconda Alyea
