### ISSUE TITLE
Degos disease

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#113]
I noticed that Orphanet list both Atrophic papulosis and malignant atrophic papulosis.  Malignant atrophic papulosis is listed in OMIM with "Degos disease" as a synonym.  Atrophic papulosis in Orphanet has Degos disease as a synonym but the page does not have any information.  Will you clarify these issues?
Thank you!

**Comment by MCecile-US14** [comment]
Hi @JTorphanet, 

Can you please take a look at this request of update and clarify the informations related to ORPHA:656071 'Atrophic papulosis' and its 2 subtypes OPRHA:656085 and ORPHA:679?

@galyea123 meanwhile please consider that ORPHA:679 is the original clinical entity we had in Orphanet (only the malignant form) but recently we created a larger phenotype as 'Atrophic papulosis' including the benign and malignant forms as both are rare. The Short description of the disorder ORPHA:656071 is currently under development.

Thank you, 
Marie-Cécile

**Comment by JTorphanet** [comment]
Dear @galyea123, 

Thank you for your message! Initially we only had "Malignant atrophic papulosis" (ORPHAcode: 679) but following a request from an European reference network (ERN) skin expert, we have reviewed the creation of "Atrophic papulosis" and "Benign atrophic papulosis". These creations have been validated based on several references of which: PMIDs 35610757 and 36353773 (very recent). In an older publication as PMID 24116834, authors said " Atrophic papulosis (Köhleimer-Degos disease or Degos disease), previously also called malignant atrophic papulosis [...]" showing the evolution of naming/knowledge. 

In recent papers (published in 2022 and 2023), it is clearly mentioned that Atrophic papulosis (ORPHAcode: 656071) is known as Degos Disease and there are represented by two different forms: the malignant and the benign (ORPHAcode: 656085). 

Do not hesitate if something is unclear. 
Best, 

Julie
