### ISSUE TITLE
ORPHA:60039 Pudendal neuralgia - name

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#116]
Dear all,

Regarding ORPHA:60039 Pudendal neuralgia, a patient has contacted us with the following message:

"I am writing to you because, as someone affected by this pathology, it seems to me that the name “pudendal neuralgia” is insufficient and can be misleading. This nerve has sensory, motor and vegetative qualities, so, in addition to the pain caused by its entrapment, affected people generally suffer motor disorders in urination and even defecation, there are many affected people who must be catheterized because the detrusor does not respond due to lack of innervation or they also suffer incontinence due to malfunction of the nerve, which also innervates the urethra. Also It is common to suffer impotence or inability to ejaculate, due to lack of correct nerve conduction and paresthesia that originates in said area. In fact, there are people who do not suffer any pain, but do suffer from incontinence or the inability to urinate or impotence. Therefore, in my humble opinion, it should not be called Neuralgia, but Neuropathy, since the word Neuralgia only refers to pain and excludes any serious motor and vegetative problem and does not express the poor condition in which this nerve and its components are usually found. consequences. I hope you take this suggestion into account."

As a result of this message, we have considered it appropriate to add in Spanish a synonym using the term "neuropathy", but we would appreciate it if you would consider modifying the name of this disease taking into account the symptoms presented.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-AysegulSenol, 

Could you please take up this request of Nomenclature update 

Thank you, 
Kind regards, 
Marie-Cécile

**Comment by Orphanet-AysegulSenol** [comment]
Dear @Orphanet-ES, 

Thank you very much for transferring this comment from the patient. I just wanted to inform you that I have started working on this issue and I will update you as soon as possible about the actions we are taking. 

Best regards, 

Aysegul

**Comment by Orphanet-AysegulSenol** [comment]
Dear @Orphanet-ES, 

I would like to inform you that following your request, and the actions below were taken to improve the main name/synonymes of this entity:

1-The main name of the entity is replaced with "Pudendal nerve entrapment syndrome" .
2-Previous old name is thus added to synonymes with the new ones including your suggestion: "Pudendal neuropathy" and "Pudendal neuropathic pain syndrome". 

Thank you for your attention, 

Best wishes, 

Aysegul
