### ISSUE TITLE
Only 1 subtype for Benign schwannoma

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#120]
Hello,

A coder has identified a disorder with only subtype: (Benign schwannoma ORPHA:252164 ; Vestibular schwannoma - ORPHA:252175).

A patient in her hospital has been diagnosed with “intracochlear schwannoma” (also a benign tumor) and she was wondering if this could constitute a second subtype for "benign schwannoma".

Let us know if you need more information.
Thank you.

**Comment by MCecile-US14** [comment]
Dear @caterina-lucano-orphanet, 

As previously discussed could you please take a look at this request and clarify the classification issue for ORPHA:252164 'Benign schwannoma' associated to the potential creation of 'intracochlear schwannoma' entity?

Thank you, 
Marie-Cécile

**Comment by caterina-lucano-orphanet** [comment]
Dear @OrphanetSwitzerland,
sorry for being late in answering your question. We are indeed aware of the one subtype situation for Benign schwannoma ORPHA:252164  and Vestibular schwannoma ORPHA:252175. There has already been a discussion and we will probably obsolete the ORPHAcode Vestibular schwannoma, as according to WHO it is a typical localization of Benign schwannoma and not a subtype/variant of the disease. We do not generally create separated locations for tumors, and we tend to follow the WHO blue books aligning with our disorder level. Therefore, I think it is safer for the coder who contacted you to code their patient simply with Benign schwannoma ORPHA:252164. Thank you,
Caterina
