### ISSUE TITLE
Mutation in ARCN1 gene - new code?

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#125]
Our expert center for dental care has got a patient with mutation in the ARCN1 gene.
The professionals have looked for other codes that might be fitting but could not find any.

https://www.omim.org/entry/617164

We ask for the creation of a new code for this disorder.

Best regards,
Lene

**Comment by JTorphanet** [comment]
Hello @LeneMartinsen, 

Thank you for your message, as for the 2 other requests I'll present this potential creation at the Orphanet committee in December. 

Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

We have validated this creation based on PMIDs: 27476655, 33154040, 35300924, 38044464 and under the main term "
Intrauterine growth retardation-micrognathia-short stature-facial dysmorphism-rhizomelic shortening syndrome" and as synonym "ARCN1-related syndrome" (ORPHAcode: 659702). 

Thank you for your patience and contribution, 

Best, 

Julie
