### ISSUE TITLE
Syndrome associated to the gene SPEN

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#127]
Hello,

Please consider the inclusion of the entity Radio-Tartaglia syndrome, associated to the gene SPEN, in the nomenclature.

The request comes from a clinician trying to code a patient with a variant de novo identified in the gene SPEN.

Please see:

- PMID: [33596411](https://pubmed.ncbi.nlm.nih.gov/33596411/) – “SPEN haploinsufficiency causes a neurodevelopmental disorder overlapping proximal 1p36 deletion syndrome with an episignature of X chromosomes in females” 
“Here, we used clinical data from 34 individuals with truncating variants in SPEN to define a neurodevelopmental disorder presenting with features that overlap considerably with those of proximal del1p36 syndrome. The clinical profile of this disease includes developmental delay/intellectual disability, autism spectrum disorder, anxiety, aggressive behavior, attention deficit disorder, hypotonia, brain and spine anomalies, congenital heart defects, high/narrow palate, facial dysmorphisms, and obesity/increased BMI, especially in females”.

- https://www.omim.org/entry/619312

Thank you

**Comment by MCecile-US14** [comment]
Dear @Orphanet-AysegulSenol, 

When you have time can you please review this request and consider the creation of this neurodevelopemental disorder associated to SPEN gene variant if it is clinically dissociated from 1p36 deletion syndrome?

Thank you, 
Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Due to a large number of requests received recently this will be treated upon the arrival of the new gene manager, as soon as he can evaluate the request.

Thank you for your understanding, 
Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @Mickael-Orphanet, 

Can you look into this issue and see if it is an entity to create when you get a chance ?
Thank you, 
Marie-Cécile

**Comment by Mickael-Orphanet** [comment]
Dear @OrphanetSwitzerland, 

I take note of the creation request for the Radio-Tartaglia syndrome. I will keep you update on the decision of the Orphanet scientific and medical committee.

Best regards,
Mickael
