### ISSUE TITLE
Lynch syndrome: why is it considered a rare disorder?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#129]
Dear Orphanet team,

We received a request from a coder regarding **Lynch syndrome (ORPHA:144).**

She wonders why this syndrome is considered rare and if she should register these patients in our Belgian Central Registry of Rare Diseases. Lynch syndrome is indeed among the most common hereditary cancer syndromes: estimates suggest as many as 1 in every 300 people may be carriers of a mutation in a gene associated with Lynch syndrome. To be more precise, the population prevalence of germline pathogenic variants in the MMR genes has been estimated at 1:279, which doesn't meet our inclusion criteria based on a prevalence less than 1/2000. On the other hand, only 3% of all cases of colorectal cancer and 2% to 3% of all cases of endometrial cancer are thought to be due to Lynch syndrome.

Is there any confusion about what is defined as "Lynch syndrome"? That is, the fact of being a carrier of the syndrome is not rare but that the cancers which will appear and which are linked to this syndrome ("LS-associated tumors") are rare, which justifies its belonging to the Orphanet classification?

Could you please give us some clarification on this?

**Documentation:**
Please find below some scientific literature on this condition:
PMID : 35177335 (https://pubmed.ncbi.nlm.nih.gov/35177335/)
PMID: 29485237 (https://pubmed.ncbi.nlm.nih.gov/29485237) 
DOI:https://doi.org/10.1016/j.gim.2022.01.014 

Thank you, kind regards,

Annabelle (Orphanet Belgium)

**Comment by MCecile-US14** [comment]
Dear @Orphanet-AysegulSenol, 

Can you please take a look at this request and clarify whether 'Lynch syndrome' is considered rare upon his clinical consequences and/or his rarity criteria, and update it accordingly?

Thank you, 
Kind regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 

Indeed as you mentioned it, in this case it is important to refer to the Orphanet Disease definition + the abstract (revised and validated by 3 ERN GENTURIS experts in 2023) specifying that ORPHA:144 corresponds to the LS-associated tumors that are considered rare "Cancer type incidences vary with the affected gene, sex, and population." SInce in fact, "the population prevalence of germline pathogenic variants in the MMR genes has been estimated at 1:279".

Hope this clarify your request
Kind regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Please also refer to the new Wiki post including Lynch syndrome mutations carriers (same answer provided with other examples) https://github.com/OD4RD/Main-Help-Desk/wiki/3.-Coding-Recommendations#coding-healthy-subjects-or-asymptomatic-carriers
