### ISSUE TITLE
Use of ICD-11 Foundation URIs in electronic health record systems?

### ISSUE THREAD

**Issue by Linngb** [OD4RD/Main-Help-Desk#130]
The Norwegian Directorate of e-health is planning for the future implementation of ICD-11 in Norway. Accordingly, they look into whether rare diseases are adequately represented in ICD-11. They state that nearly all ORPHA entities at the disorder level (except 5-6 disorders) are represented in ICD-11 by a URI in the Foundation. Furthermore, they believe that they can use the URIs for specific representation of these entities in the EHR system, even if there is no specific code in the MMS. For example:
 
ORPHA:912 Zellweger syndrome which is aligned to ICD-11 code 5C57.0 Disorders of peroxisome biogenesis and has the Foundation URI : http://id.who.int/icd/entity/226023718
 
However, in the Main-Help-Desk Wiki page about Alignments with other terminologies, it says that “Indeed, a small proportion of the Orphanet clinical entities is included in ICD-11 and most of them are presented in the Foundation, and not in the MMS. These diseases are represented by a URI that cannot be used in medical/public health practice.”
 
Could you please clarify why Foundation URIs cannot be used in clinical practice?
 
Thank you.
Best regards,
 
Linn (Orphanet Norway)

**Comment by JTorphanet** [comment]
Dear @Linngb, 

Thank you for your message and for raising some important points. 

The section on ICD-11 alignment is no longer up-to-date as we have actively started the collaboration with WHO to align ORPHAcodes and determine the representation of rare diseases. The first phase is almost finished and has allowed us to evaluate the number of rare diseases represented in the Foundation and in the MMS. To date, we have identified less than 1000 ORPHAcodes at the disorder level represented in the MMS and fewer than 4000 ORPHAcodes at the disorder level in the Foundation (out of more than 6300 disorders). The second phase has just begun and consists to attribute a ICD-11 code for ORPHAcodes not registered in ICD-11 acccording to Orphanet's rules. Less than 2000 disorders remain to be aligned. 

If it is possible, we would be very interested to have more details on the comparison made by the Norwegian Directorate of e-health to better understand the result of 5/6 disorders. 

Moreover, Orphanet is not able to provide coding recommendations for ICD terminologies but only for the use of ORPHAcodes. I suggest you to consult the following links or contact the WHO team directly for further information: 
[https://icd.who.int/en/docs/ICD-11%20Implementation%20or%20Transition%20Guide_v105.pdf](url)
[https://icdcdn.who.int/icd11referenceguide/en/html/index.html](url)

Indeed, it was a mistake to mention the use of MMS code and/or URI in the wikipage and we will make a complete update of the wikipage to correct and clarify these points. 

Thank you very much, 
Best regards, 

Julie

**Comment by Linngb** [comment]
Dear @JTorphanet,

Thank you for updated numbers on disorder level ORPHAcodes represented in the MMS and Foundation, respectively. 
I will forward this to The Norwegian directorate of e-health, and ask for details on their result of only 5/6 disorders missing.

Thanks also for updating the wikipage.

Best regards,
Linn
