### ISSUE TITLE
Imagawa-Matsumoto syndrome

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#131]
Hi!  I was not able to find this condition in Orphanet. 
Orphanet page for Weaver syndrome is linked to OMIM page for this condition as well as for Cohen-Gibson syndrome and Weaver syndrome.  
While both Cohen-Gibson syndrome and Imagawa-Matsumoto syndrome are both considered Weaver-like syndromes they are different entities.
Please see this recent review for Imagawa-Matsumoto syndrome: https://onlinelibrary.wiley.com/doi/10.1111/cge.14296 

Thank you for your review!  Gioconda Alyea

**Comment by MCecile-US14** [comment]
Dear @Orphanet-AysegulSenol, 

Could you please take on this request linked to #128 as it concerned related entities.
@galyea123 this might be treated in 2024 as our current workload is quite full for the end of the year :)

Thank you 
Kind regards, 
Marie-Cécile

**Comment by Orphanet-AysegulSenol** [comment]
Dear @galyea123, 

I would like to inform you that Imagawa-Matsumoto syndrome will be created as a new entity but as I just mentioned under your request of Cohen-Gibson syndrome, it will take some time to display it at the website due to some technical issues. 

Best wishes, 

Aysegul

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________

**Comment by Orphanet-AysegulSenol** [comment]
Dear @galyea123, 

Just wanted to update you on the creation of the entity Imagawa-Matsumoto syndrome. Orpha code: 659463 is now available at Orphanet website. 

Best wishes, 

Aysegul

**Comment by galyea123** [comment]
Hi Aysegul! Thank you for the update!  Best, Gioconda
