### ISSUE TITLE
Syndrome associated to the gene LEMD2

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#132]
Hello,

Please consider the inclusion in the nomenclature of the clinical entity associated to the gene LEMD2: Marbach-Rustad progeroid syndrome.

The request comes from a clinician with a patient diagnosed last year. She was under regular follow-up for several years and had a negative whole exome sequencing a few years ago. That was repeated in 2022 and revealed the mutation in the LEMD2 Gene.
She has progeroid features (dysmorphic face, incomplete dentition, microcephaly, short stature, exostoses, early stage arteriosclerosis without stenosis) and partial lipoatrophy with insulin resistance, hepatomegaly and liver steatosis, hypertriglyceridemia and polycystic ovary syndrome. The family history is negative.

References:
-	PMID: 30905398: The Discovery of a LEMD2-Associated Nuclear Envelopathy with Early Progeroid Appearance Suggests Advanced Applications for AI-Driven Facial Phenotyping.
-	https://www.omim.org/entry/619322

Thanks

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Thank you for your request. Due a high number of requests, this creation will be treated as soon as possible, early 2024.

Thank you for your understanding, 
Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @Mickael-Orphanet, 

Could you please take this issue in your list to consider for creation ?
Thank you, 
Marie-Cécile

**Comment by Mickael-Orphanet** [comment]
Dear @OrphanetSwitzerland,

I add to my list the creation request for the Marbach-Rustad progeroid syndrome. I will keep you update on the decision of the Orphanet scientific and medical committee.

Best regards,
Mickael

**Comment by OrphanetSwitzerland** [comment]
Thank you!
