### ISSUE TITLE
API: Orphanet nomenclature in FHIR format?

### ISSUE THREAD

**Issue by OrphanetDE** [OD4RD/Main-Help-Desk#134]
Are there any plans to provide the nomenclature data in FHIR format in the (near) future?

**Comment by davidlagorce** [comment]
Dear user, thank you for your comment. 
There is no near plan to distribute the Orphanet nomenclature in a FHIR format as HL7. Nevertheless, you can access to nomenclature data by using the Orphacodes API. https://api.orphacode.org/
Best regards
David

**Comment by MCecile-US14** [comment]
Dear @OrphanetDE, please find below complementary informations regarding this request:
There is no future plan to deliver the Pack in FHIR format. Assuming you will use the Orphadata API then you have to adapt/update the backend accordingly in your system.
