### ISSUE TITLE
Prenatal coding

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#139]
Hello,

We have a few questions to the coordinating team and to the countries implementing the Orphacodes concerning the prenatal diagnostics:

-	Are they being coded in your country?
-	Who do you code?
-	Do you code in the case of a miscarriage?

Maybe this can be discussed in an open session.
Thanks

**Comment by MCecile-US14** [comment]
Thank you @OrphanetSwitzerland for your request. 
I am taking note of the questions and will add it to the next Open Coding & Nomenclature Open session' agenda (14/12). I will send a reminder to the session few days before so that participating countries can be aware of the topics.

Kind regards, 
Marie-Cécile

**Comment by Orphabe** [comment]
Dear all,

We (the Belgian hub) were not able to attend the open session on 14/12 but we are interested in this topic. Could you be so kind to post here a brief summary of the discussions and recommendations concerning this issue?

Thank you, kind regards,

Annabelle

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 
During this open session (http://network.orphanet.org/wp-content/uploads/C_Trainings/Open_sessions2023/Nomenclature_OpenSessions_WP4/14122023_Nom_OpenSession3.pdf), not all National Hubs were represented (about only 6 country), most of the NH did not had the chance to look before about their national recommendations and way of coding about prenatal diagnosis; and assessed the evident difficulties to get clear view and answers about it. 
This is a difficult and very specific issue for which Orphanet cannot provide official recommendations as it is so dependant on each national legislation, ethics, political statments...
Of course, we will always provide clarifications regarding diagnosis of each prenatal ORPHAcode we produce (perimeter, alignments ...) and I invite you to look to previous issue #79 we discussed here about ORPHA:95431 'Twin to twin transfusion syndrome'  and ORPHA:439167 'Placental insufficiency'.

Another idea, is to organise at the european level a collegial rountable meeting with health EU representatives, health care providers, MS medical board of different countries where Orphanet could be invited as a Rare Diseases Nomenclature provider.

Please let me know if you want to reopen the topics to a next Nomenclature Open session with more participants present

Kind Regards, 
Marie-Cécile
