### ISSUE TITLE
ORPHA:93569 Polymyalgia rheumatica - prevalence

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#140]
Dear Moi, 

A Spanish professional has answered us because he questions the "rarity" of Polymyalgia rheumatica - ORPHA:93569.
According to her comments, the literature indicates that it is considered the second most common rheumatological disease in the elderly.

I have searched for publications about it and I have found the following article, where it is said that:
"_The prevalence is estimated at 700/100.000 individuals aged >50 years_"
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10623218/ 
So, if I have not misunderstood, it far exceeds the definition of a rare disease.

Could you verify if it is really a rare disease or not?

Thanks for your help.

Kind regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Dear Moi,

The expert provided me with the following publication:

Clinical manifestations and diagnosis of polymyalgia rheumatica
https://www.uptodate.com/contents/clinical-manifestations-and-diagnosis-of-polymyalgia-rheumatica?search=polimialgia%20reumatica&source=search_result&selectedTitle=1~110&usage_type=default&display_rank=1

Kind regards, 

María Elena

**Comment by moi-epiUS14** [comment]
Hi Maria Elena, 

Thank you for your message and the detailed information. 

I did take a look at the entity, and as suggested, it seems to be NOT rare in Europe. (PMIDs: 31480261, 32868305, 36749363, 37928511)
I will bring this matter to the Disease team and request to remove the entity from our database. 

Thanks again :) 

Best, 
M

**Comment by Orphanet-ES** [comment]
Hi Moi,

Thanks for your quick response.

I will inform the Spanish expert, as soon as this matter is confirmed by the Disease team.

Have a nice day!

María Elena

**Comment by moi-epiUS14** [comment]
Maria Elena, 

I just wanted to tell you that we just had a Disease meeting, and it was decided that Polymyalgia rheumatica is indeed NOT rare, and we will be removing the entity from our nomenclature/database. 

Again, thanks for spotting a non-rare entity. 

Happy holidays :) 

M

**Comment by Orphanet-ES** [comment]
Thank Moi for clarifying this issue so quickly.
I will inform the Spanish expert.

Happy holidays :)

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

I am closing this issue as completed now but just to let you know that all current decisions cannot be implemented as our internal data base tools are all down due to IT issue, still unsure when It will be fully back but as soon as we can we will implement all disease meeting validated decisions (non rare, deprecation, obsolescence flags; modification and creation into the database)

Thank you for your understanding, 
Kind Regards, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 ,

I return to the topic of this disorder since I have seen that it continues to appear on the Orphanet website.
It does not have any associated information, but it has not yet been indicated that it is NOT rare in Europe, and it is still active.

Kind regards, 

María Elena

**Comment by caterina-lucano-orphanet** [comment]
Hello Maria Elena, 
thank you for your feedback, I had a look and this is just a matter of a delay in inactivating the entity. I confirm indeed that the decision has been taken and will shortly be implemented.

Thanks,
Caterina
