### ISSUE TITLE
Request to add new conditions related to HNRNP gene mutations

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#141]
We were recently contacted by one of the authors of several publications related to the HNRNP gene family.  They are writing reports for NORD and also there is a support organizations for patients and families affected with this condition that is requesting to have the reports. Please look at the information below and consider adding the terms that are still not listed in Orphanet.

HNRNPH1: the condition related to this gene mutations is listed as neurodevelopmental disorder with craniofacial dysmorphism and skeletal defects (See OMIM: https://www.omim.org/entry/620083) but it is not in Orphanet yet. 
 
HNRNPH2-Related Neurodevelopmental Disorder has a GeneReview already and we list it as “intellectual disability, X-linked, syndromic, Bain type” as per OMIM. (it is still not in Orphanet)
 
HNRNPC: There is still not name for a condition related to HNRNP gene mutations and it is not listed in Orphanet or OMIM (and hence, not listed in MONDO either) but “data strongly support the inclusion of HNRNPC to the family of HNRNP-related neurodevelopmental disorders.” and there are more than three people reported  [https://pubmed.ncbi.nlm.nih.gov/37541189/ Please see the attached link to consider adding the condition.  

HNRNPK:  This one is already in Orphanet as "Neurodevelopmental disorder-craniofacial dysmorphism-cardiac defect-skeletal anomalies syndrome" and in OMIM as "Au-Kline syndrome" and also there is a GeneReview.  For this one I do not have any request besides adding all the former synonyms - Okamoto syndrome -  (it includes Neurodevelopmental disorder-craniofacial dysmorphism-cardiac defect-skeletal anomalies syndrome due to 9q21.3 microdeletion and Neurodevelopmental disorder-craniofacial dysmorphism-cardiac defect-skeletal anomalies syndrome due to a point mutation). 

HNRNPR:  The condition related to mutations in the HNRNPR gene is in OMIM and MONDO as "Neurodevelopmental disorder with dysmorphic facies and skeletal and brain abnormalities".  It is not in Orphanet yet.

SYNCRIP-Related Neurodevelopmental Disorder:  This is still not in OMIM or Orphanet and will be in MONDO soon. 
 There is however many published articles. https://pubmed.ncbi.nlm.nih.gov/34157790/ (one of the NORD RD CoE members wrote a report already).

Other relevant sources:
https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-021-00870-6 
https://link.springer.com/article/10.1007/s00439-021-02412-x
https://www.researchgate.net/figure/Relationship-of-HNRNP-related-disorders-to-each-other-and-to-similarly-presenting_fig8_350989036
https://www.hnrnp.org/newlydiagnosed

Thank you! Gioconda Alyea

**Comment by MCecile-US14** [comment]
Dear @Mickael-Orphanet, 

When you have time could you please look into this issue and see if HNRNP gene family' related phenotypes are to be included in Orphanet Nomenclature?
Thank you, 
Marie-Cécile

**Comment by Mickael-Orphanet** [comment]
Dear @galyea123, 

I add to my list all the creation requests for disorders linked to HNRNP gene family. I will keep you update on the decision of the Orphanet scientific and medical committee.

Best regards,
Mickaël

**Comment by galyea123** [comment]
Thank you Mickaël!  Very appreciated!

**Comment by Mickael-Orphanet** [comment]
Dear @galyea123, 

We have reviewed all the demands of creations concerning HNRNP gene mutations. Here is the list of decisions: 

HNRNPH1:  "Neurodevelopmental delay-brain malformations-skeletal defects-intellectual disability syndrome" under ORPHA:662207

HNRNPH2:"Neurodevelopmental delay-intellectual disability-skeletal defects syndrome" under ORPHA:662198

HNRNPC : Not created linked to "Non-specific syndromic intellectual disability" under  ORPHA:528084

HNRNPR: "Neurodevelopmental disorder-brain malformation-facial dysmorphism-brachydactyly syndrome" under ORPHA:662189

SYNCRIP: Not created SYNCRIP linked to Non-specific syndromic intellectual disability ORPHA:178469

The changes will only be visible on the website next week. 

Best regards, 
Mickaël

**Comment by galyea123** [comment]
Thank you Mickael!
