### ISSUE TITLE
Pathology report and ORPHAcodes

### ISSUE THREAD

**Issue by OD4RDFIN** [OD4RD/Main-Help-Desk#145]
Hi,

it would be valuable if pathologists could select an ORPHAcode to their report if histology shows rare form of cancer or some other disease. Then, clinical oncologists and other clinicians would have easier to use the right ORPHAcode in the electronic patient report.

Do any countries have pathologists involved in using ORPHAcodes? In Finland, pathologists don´t currently use them and more awareness and education are needed.

BR,

Satu Wedenoja 
Finnish Institute for Health and Welfare

**Comment by uunter98** [comment]
Hi Satu,
this will be different in every country and system; in our hospital, clinicians do the official coding, but pathologists of course apply codes in their registries etc. I/we offer training to everyone who is interested of course, but it will be mandatory only for clinicians in designated centers of expertise / ERN centers.
KR
Ursula

**Comment by MCecile-US14** [comment]
Dear @OD4RDFIN, 

Thank you for your message.
Indeed, as @uunter98 mentioned this seems to be country specific depending on each healthcare system organization, what options are made available in EHR and HIS to allow each specialists and pathologists to adapt to their clinical practice.
Orphanet National Hubs are made to promote, advise and facilitate the use/implementation of ORPHAcodes based on the national policy and specifications.

@Satu this could be a topic to bring to the next Nomenclature/Coding Open session (22/02/24) if you or someone from Orphanet Finland plan to be present ? 
Please let me know if I should add this on the list
Kind Regards, 
Marie-Cécile
