### ISSUE TITLE
Update disease abstract Locked-in syndrome (ORPHA:2406)

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#149]
Hi,

The Norwegian MD and professor Frank Becker is an expert on locked-in syndrome and has recently published a study including 51 patients: https://www.neurology.org/doi/10.1212/WNL.0000000000207577

He has offered to update the disease abstract for locked-in syndrome (not been updated since 2012).
His e-mail is Frank.Becker@sunnaas.no

Is this an option for Orphanet? If so, how do we proceed?

Kind regards,
Lene

**Comment by MCecile-US14** [comment]
Dear Lene, 

Thank you for your message and the kind expert suggestion to update the abstract
Indeed, I see that Locked In syndrome' abstract is from 2012, I am not sure if it is on the line for revision (we are currently updating older entities) but we are Always seeking for expert reviewers volunteers. 
I am transfering your request to the project manager in charge of the medical writing of abstract with experts as she is not present on the GitHub. She will reach back the expert to let him know about the procedure.

Thanks for your help
Kind Regards, 
Marie-Cécile

**Comment by LeneMartinsen** [comment]
Great! Thanks a lot, Marie-Cécile.

Best,
Lene
