### ISSUE TITLE
Nicolau syndrome

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#151]
Hello,

Please consider the inclusion in the nomenclature of the Nicolau syndrome (synonyms: Livedo-like dermatitis, Embolia cutis medicamentosa).

The request comes from a coder at a Swiss hospital. They have a patient with this “iatrogenic syndrome initially described to occur after intramuscular injections”.

References:
• PMID: 20808597: Nicolau Syndrome: An Iatrogenic Cutaneous Necrosis
• https://www.sciencedirect.com/topics/pharmacology-toxicology-and-pharmaceutical-science/nicolau-syndrome

Thank you

**Comment by Orphanet-AysegulSenol** [comment]
Dear @OrphanetSwitzerland, 

I would like to inform you that "Nicolau syndrome" is now created (ORPHA:664787). "Livedo-like dermatitis" and  "Embolia cutis medicamentosa" were also added as synonymes. 

Thank you for the useful information you shared and also for your attention.

Best wishes,

Aysegul
