### ISSUE TITLE
Adding a new term:  Fournier gangrena

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#156]
Fournier gangrene refers to the death of body tissue of the genitals and/or perineum. Signs and symptoms of the condition include genital pain, tenderness, redness, and swelling with a rapid progression to gangrene. Although the condition can affect men and women of all ages, it is most commonly diagnosed in adult males. Most cases of Fournier gangrene are caused by an infection in the genital area or urinary tract. People with impaired immunity (i.e. due to diabetes or HIV) have an increased susceptibility to the condition. It is considered a rare form of necrotizing fasciitis. 

Please see: 
https://rarediseases.org/rare-diseases/fournier-gangrene/
https://rarediseases.info.nih.gov/diseases/10912/fournier-gangrene
https://karger.com/uin/article/97/3/249/323020/Fournier-s-Gangrene-Epidemiology-and-Outcomes-in
https://emedicine.medscape.com/article/2028899-overview
https://www.ncbi.nlm.nih.gov/books/NBK549821/
https://dermnetnz.org/topics/fournier-gangrene
https://wjes.biomedcentral.com/articles/10.1186/s13017-018-0187-0

Thank you, Gioconda Alyea

**Comment by MCecile-US14** [comment]
Dear @galyea123, 

Thank you for your suggestion for inclusion. We will evaluate this request in the coming Orphanet disease meeting cycleand keep you posted in case of creation of a new ORPHAcode
Best regards, 
Marie-Cécile

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________

**Comment by MCecile-US14** [comment]
Dear @galyea123, 

Orphanet medical and scientific committee decided to not create a specific entity for 'Fournier Gangrena'. As mentioned in the references you sent me Fournier gangrena is described as a localized form of necrotizing fasciitis (scrotum, perianal and genital areas.
"Fournier gangrene, a relatively rare form of necrotizing fasciitis, is a rapidly progressive disease that affects the deep and superficial tissues of the perineal, anal, scrotal, and genital regions"; "Fournier gangrene is a specific form of necrotizing fasciitis, localized on the external genital organs, as well as in the perianal region" PMID:29949811 (2018)

Thus, Orphanet considers that 'Necrotizing fasciitis' is part of ORPHA:440368 'Necrotizing soft tissue infection', NSTI (incl. Keywords: Necrotizing cellulitis, adipositis, erysipelas, fasciitis, and myositis), an entity initially created after an Orphan designation (treatment for necrotizing soft tissue infection). 

Also Fournier gangrena "results from polymicrobial aerobic and anaerobic synergistic infection of the fascia and subcutaneous soft tissue." as resumed by ORPHA:44038' definition.
**To be specific I included 'Fournier Gangrene' as a keyword of ORPHA:44038.**

Please note than from now on (new version of our website online) all Nomenclature changes will be visible the next week (and not in the next 24 hours like before).

Hope this clarify your request.
Kind Regards,
Marie-Cécile
