### ISSUE TITLE
Adding a new term: Frey syndrome

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#157]
This syndrome is in [OMIM](https://omim.org/entry/144100) and GARD [https://rarediseases.info.nih.gov/diseases/6467/disease] and there is a NORD report [https://rarediseases.org/rare-diseases/frey-syndrome/]  While it is mostly a complication Orphanet has conditions in this category as well.

Description

Frey syndrome, also known as auriculotermporal syndrome o gustatory sweating is a rare disorder that most often occurs as a result of surgery in the area near the parotid glands. The parotid glands are the largest salivary glands in the body located just below the ears on either side of the face. The main symptoms of Frey syndrome are undesirable sweating and flushing occurring on the cheek, temple (temporal region), or behind the ears (retroauricular region) after eating certain foods, especially those that produce a strong salivary response. Symptoms are often mild and well-tolerated. In some people , symptoms may be more severe and therapy may be necessary. The exact underlying mechanisms that cause Frey syndrome are not fully understood. Frey syndrome most often occurs as a complication of surgery to the area of the face near the parotid glands. 

Thank you, Gioconda Alyea

**Comment by MCecile-US14** [comment]
Dear @JTorphanet, 

Can you please look to this potential new entity to create ?
Thank you
Marie-Cécile

**Comment by JTorphanet** [comment]
Dear @galyea123, 

The Orphanet committee has just validated the creation of an ORPHAcode for the Frey Syndrome ORPHA:662240. 
It will be visible next week on our website. 

Thank you for your contribution! 
Best, 

Julie
