### ISSUE TITLE
How could we establish the aligment with ICD-10-CM instead of ICD-10?

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#16]
Some users have informed us that they have problems to align ORPHAcodes with the Spanish version of the ICD-10-CM (Clinical Modification) which differs from ICD-10 to which Orphanet establishes the alignments.

**Comment by JTorphanet** [comment]
Hello Orphanet-ES, 

Orphanet is an international classification and by definition, aligned only with other international medical classifications. We understand that countries needed to update ICD10 over time while waiting for ICD11, but it is technically not possible to align ORPHAcodes with all the country-specific ICD10-CM systems. Most of the time, the “national” ICD10-CM database is more granular; our general advice is to use the alignment provided by Orphanet to help you to find the right group and use it to refine the alignment to the national ICD10-CM step by step. 

Best, 

Julie

**Comment by Orphanet-ES** [comment]
Hello Julie,

Thanks for your answer and for your recommendation of using the alignment provided by Orphanet to help to find the right group.
If they raise this issue again, I'll send them your answer.

Best, 

María Elena
