### ISSUE TITLE
New ORPHAcode for mutation ARPC4?

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#160]
Hi,

One of our expert centres has a patient with a mutation in the ARPC4 gene and a phenotype compatible with OMIM 620141:
https://www.omim.org/entry/620141
No other diagnosis has been found to fit the patient's clinical symptoms.

Can Orphanet consider creating a new entity for this mutation-phenotype relationship?

Kind regards,
Lene

**Comment by Linngb** [comment]
Dear all,

Conserning case reporting to the Norwegian registry on rare disorders, several clinicians have recently requested an ORPHA-code for Developmental delay, language impairment, and ocular abnormalities (DEVLO) - the OMIM phenotype (#620141) associated with the above-mentioned mutation in the ARPC4 gene.  

Best regards,
Linn

**Comment by JTorphanet** [comment]
Dear @Linngb, @LeneMartinsen, 

This issue has already been discussed and its implementation will be validated on the following Monday. I will keep you update. 

Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @Linngb, @LeneMartinsen, 

Based on the medical and scientific litterature, Orphanet committee has validated the creation of this entity under ORPHA:662762 and named "Motor delay-microcephaly-speech impairment-ocular abnormalities syndrome" (Synonym: ARCP4-related syndrome). I have already linked the OMIM number as exact match. 

This creation will be visible on our website next week. 

Thank you for your contribution, 
Best regards, 

Julie

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

Yes you have this error page because we have not yet included these entities in the classification. We will do our best to do it ASAP.

Sorry for the delay and inconvenience, 
Best, 

Julie

**Comment by LeneMartinsen** [comment]
Thank you for letting us know, @JTorphanet !

FYI @Linngb 

Best,
Lene
