### ISSUE TITLE
Creation of an ORPAcode for midface hypoplasia, hearing impairment, elliptocytosis, and nephrocalcinosis (MFHIEN)

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#161]
Dear all, 

A Spanish geneticist has requested the creation of an specific ORPHAcode for "midface hypoplasia, hearing impairment, elliptocytosis, and nephrocalcinosis (MFHIEN)", [OMIM 300990](https://omim.org/entry/300990), caused by hemizygous mutation in the AMMECR1 gene ([300195](https://omim.org/entry/300195)) on chromosome Xq23.

_Midface hypoplasia, hearing impairment, elliptocytosis, and nephrocalcinosis is an X-linked recessive disorder with onset of features in early childhood. Anemia is sometimes present. Some patients may show mild early motor or speech delay, but cognition is normal (summary by [Andreoletti et al., 2017](https://omim.org/entry/300990#1))._

Currently, the OMIM 300990 is linked to the ORPHA:86818 Alport syndrome-intellectual disability-midface hypoplasia-elliptocytosis syndrome, together with OMIM: [300194](http://omim.org/entry/300194), but only this last OMIM would correspond to the description and name of this syndrome.

The Spanish expert argues that she has encountered cases that don't correspond to ORPHA:86818, which is why she considers that it is necessary to create a specific ORPHA for the presentation of the syndrome MFHIEN.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @JTorphanet, 
Could you please look into this issue to clarify and see if it requires a new creation
Thank you, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear @JTorphanet ,

Have you been able to look at this request?

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

Thank you for your message, I have not yet reviewed this creation. Moreover, I have too many requests for the next disease meeting cycle, I will present this request to the Orphanet committee in April. 

Thanks for your patience, 
Best, 

Julie

**Comment by Orphanet-ES** [comment]
Dear all,

Have you had the opportunity to discuss the creation of this entity in the Orphanet committee in April?

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Unfortunately since Julie left, she did not get the chance to present this request before. This has been re dispatch to another Nomenclature manager and is in the line for the Orphanet disease meeting in July (if not September).
Please note that the standard delay for ORPHAcode creation/evaluation you might want to share with experts is 6 months

Thank you for your understanding, 
Kind Regards, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 ,

Thanks for your answer.

Since I had seen that Julie had left the team, I was wondering if this topic had been discussed or not.
I note that it may be discussed at the next disease meetings in July or September, and the 6 month range for decision making.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Very sorry for the delay, this request fell down my radar. 
@Seed-Orphanet do you think you could prioritize this request of creation for the coming disease meeting cycle? 
Please ask any help to @Mickael-Orphanet regarding the OMIM phenotype and gene mutation involved

Thank you for your understanding, 
Marie-Cécile

**Comment by Seed-Orphanet** [comment]
Dear @Orphanet-ES 

I apologize for the delay but I have good news, this request has been treated and we are creating and ORPHAcode for this disorder. It will soon be available for consultation on the Orphanet website.
Here is the message that you can kindly transfer to the geneticist:

Based on current literature and experts advice, Orphanet medical and scientific committee has validated the creation of 'Midface hypoplasia-hearing impairment-elliptocytosis-nephrocalcinosis syndrome', ORPHA:688581. Major clinical features are: sensorineural hearing loss, elliptocytosis, nephrocalcinosis, midface hypoplasia, cleft palate and short stature. Patients show motor and speech developmental delay, but cognitive development is unaffected. More variable features include patent foramen ovale, anemia, small mouth and hypotonia. The prevalence is unknown but the rarity has been established.

Kind regards,
Seed

**Comment by Orphanet-ES** [comment]
Dear @Seed-Orphanet 

Thanks for your help.
I will translate the name into Spanish and inform the expert who requested the creation of this ORPHA.

Kind regards, 

María Elena
