### ISSUE TITLE
Stüve-Wiedemann syndrome

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#167]
Dear all,

In relation to the file Modified_diseases_December-2023, we have a doubt regarding "Stüve-Wiedemann syndrome".

First of all, this name appears as Pat (ORPHA:3206) and as Wrd (ORPHA:656283), which can be confusing for our users.

In the case of ORPHA:656283 ([Autosomal recessive combined immunodeficiency due to complete IL6ST deficiency](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=31925), according to the assigned OMIM [619751](http://omim.org/entry/619751), it seems to correspond to "Stuve-Wiedemann syndrome**-2**".

On the other hand, ORPHA:3206 ([Stüve-Wiedemann syndrome](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=3233)), according to the assigned OMIM [601559](http://omim.org/entry/601559) would correspond to "Stuve-Wiedemann syndrome**-1**".

In the first case (ORPHA:656283), do you consider it appropriate to change the Wrd to "type 2" so as not to confuse both syndromes?

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

Thank you to raise this point, indeed it could be confusing.
AR complete IL6ST deficiency (ORPHA: 656283) has sometime been considered as a type of Stüve-Wiedemann syndrome (e.g. Minegishi et al. 2021, PMID: 34419355), but it presents with additional features of congenital thrombocytopenia, eczematoid dermatitis, renal abnormalities, and defective acute-phase response (Chen et al. 2021, PMID:34044328). This clinical phenotype is sometime referred to as an 'extended Stüve-Wiedeman syndrome' (e.g. Chen et al. 2021 PMID:34044328).

To clarify, we will do some nomenclature changes: 
- ORPHA: 3206: add Stüve-Wiedeman syndrome type 1 as synonym 
- ORPHA: 656283: remove the keyword Stüve-Wiedeman syndrome and add as synonym Stüve-Wiedeman syndrome type 2

These modifications will be visible in the next coming days. 
Do not hesitate to come back to us if you have any other questions. 

Best, 

Julie
