### ISSUE TITLE
Hereditary ATTR amyloidosis ORPHA:271861 - add OMIM 105210 

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#172]
Dear all,

A Spanish coder has suggested to link [OMIM 105210 ](https://omim.org/entry/105210) to Hereditary ATTR amyloidosis ORPHA:271861.
This OMIM is already linked to its subtypes:

- ATTRV122I amyloidosis ORPHA:85451
- ATTRV30M amyloidosis ORPHA:85447

I have searched in the Wiki and in the Open session presentations if you had communicated rules for assigning OMIM codes to the disorders collected in Orphanet, but I have not found anything about it.
In any case, I understand that a disorder is assigned the OMIM codes of its children, whether the relationship remains exact (E), or becomes a BTNT relationship, so there would be no problem when assigning this OMIM to the disorder ORPHA:271861.

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

Indeed, the OMIM number 105210 should be linked to ORPHA:271861 with an exact relationship contrary to ORPHA:85451 and ORPHA:85447 with a NTBT relationship because they are subtypes. 

It will be visible in the next 2 days. 
Best, 

Julie
