### ISSUE TITLE
Change OMIM 619239 from ORPHA:528084 to ORPHA:178469 

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#173]
Dear all,

A Spanish coder has sent us the following comment: 

"_The OMIM [619239](https://omim.org/entry/619239) "Neurodevelopmental disorder with or without autism or seizures" phenotype is autosomal dominant and therefore best fits [ORPHA:178469](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=18028) despite its accompanying traits.
Assigning this and other OMIM phenotypes with known inheritance patterns to [ORPHA:528084](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=27491) could be misleading._"

I am not clear how you define syndromic and non-syndromic disorders, but reviewing the OMIMs assigned to ORPHA:178469 (according to the name, non-syndromic), similar phenotypes to OMIM 619239 have been associated.

For example, OMIM [614254](https://omim.org/entry/614254) is a "Neurodevelopmental disorder with or without hyperkinetic movements and seizures, autosomal dominant."

Please review the OMIM assigned to both disorders taking into account the coder's comments.

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Hello @Orphanet-ES, 

I will take a look into this issue. I will let you know ASAP. 

Best, 
Julie

**Comment by Orphanet-ES** [comment]
Dear @Mickael-Orphanet ,

Thanks for the clarification.

I have reviewed the workflow and the description of the disease according to OMIM, and I understand that it is considered syndromic because "_Additional variable systemic features may also be present, such as cardiac defects, failure to thrive, or brain imaging anomalies_", otherwise it would be considered non-syndromic. I'm right?

From what I see, the line between whether it is a syndromic or non-syndromic disease is very fine, because the characteristics that make it syndromic are not always present.

In any case, if it has been decided that this phenotype corresponds to ORPHA:528084, you should also consider linking the causative gene [CUL3](https://omim.org/entry/603136).

I will transmit your explanation to the expert.

Kind regards, 

María Elena

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES, 

Yes you are right, when there is presence of congenital anomalies that are present in less than 30% or non specific facial dysmorphism we link the gene to Non-specific syndromic intellectual disability. 

I will review the demand concerning CUL3 gene. 

Thank you for your demand. 

Best regards, 
Mickaël
