### ISSUE TITLE
Link OMIM 612621 to ORPHA:544254 SYNGAP1-related developmental and epileptic encephalopathy

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#176]
Dear all,

A Spanish coder suggests linking [OMIM 612621](https://omim.org/entry/612621) to [ORPHA:544254 ](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=28070)SYNGAP1-related developmental and epileptic encephalopathy, since it is the only phenotype associated with the gene that causes this pathology ([SYNGAP1](https://omim.org/entry/603384)).

In fact, on Orphanet, the OMIM 612621 is only assigned to [ORPHA:178469](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=18028) Autosomal dominant non-syndromic intellectual disability, although the [gene](https://www.orpha.net/consor/cgi-bin/Disease_Genes.php?lng=EN&data_id=18361) is related to 4 disorders.

When there is a single phenotype associated with a gene, how do you select which disorders that OMIM can be associated with and which ones it cannot?

I would like to be able to understand it to transmit it to the expert.

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

I have deeper rechecked this issue and it was easier than I imagined.
Specifically in this case, ORPHA:544254 SYNGAP1-related developmental and epileptic encephalopathy was independently recognized as an independent entity. By consequence, we removed OMIM 612621 from ORPHA:442835 Undetermined early-onset epileptic encephalopathy and now, from ORPHA:178469 Autosomal dominant non-syndromic intellectual disability. 

Everything was corrected. 

Thank you for raising this point, 
Best, 

Julie

**Comment by Orphanet-ES** [comment]
Dear @JTorphanet 

I have searched by OMIM 612621 on Consor, and ORPHA:178469 Autosomal dominant non-syndromic intellectual disability is still linked to that OMIM.
Could you confirm that it is already unlinked in the database? Because it has been more than a week since you notified me and it is still linked in Consor

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

This OMIM is well removed from ORPHA:178469 in our internal tool. It is probably just a bug. I will mention it to the IT. 
Please, re-check next monday and do not hesitate to come back to us if it is still present. 

Thank you, 
Best, 

Julie

**Comment by Orphanet-ES** [comment]
Dear @JTorphanet ,

OMIM 612621 is no longer linked to ORPHA:178469 so the bug has been corrected.

Thanks for your help,

María Elena
