### ISSUE TITLE
Link OMIM 612313 to ORPHA:576278 SATB2-associated syndrome

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#177]
Dear all, 

A Spanish coder proposed linking [OMIM 612313](https://www.omim.org/entry/612313) to [ORPHA:576278](https://www.orpha.net/en/disease/detail/576278) SATB2-associated syndrome, and also add the synonym Glass syndrome.

I have seen in [GitHub](https://github.com/OD4RD/Main-Help-Desk/issues/21#issue-1382099968) that we already discussed the topic of Glass syndrome, and that it is linked as a keyword because the equivalence is not exact, what seems good to me.
It is a keyword for ORPHA:576278, ORPHA:251028, ORPHA:251019, but I don't understand why is not related to the subtype [ORPHA:576283](https://www.orpha.net/en/disease/detail/576283) SATB2-associated syndrome due to a pathogenic variant. Is this a mistake?

I have also reviewed the CRtotalRM file and, although it is indicated that the relationship is not exact with the OMIM 612313, it will be assigned to all disorders related to Glass syndrome. However, in the end it has not been assigned to any.
Maybe I've gotten lost in the process, but has there been a change of mind on this?

Kind regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Dear Julie,

Thanks for your reply.

When I searched the OMIM yesterday, I couldn't find any associated disorder, but since the new website was being launched just yesterday, perhaps the old one wasn't working well... or I got lost and didn't look for the information correctly :(

I will check the information you added next Monday.

Best regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Hi @JTorphanet ,

I have verified that today the OMIM appears associated with all disorders, but regarding Glass syndrome as keywords, why have you not associated it with the subtype ORPHA:576283 [SATB2-associated syndrome due to a pathogenic variant](https://www.orpha.net/en/disease/detail/576283)?

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

Clearly, this is an oversight. I have just added this keyword to ORPHA:576278. It will be visible next week. 

Best, 

Julie
