### ISSUE TITLE
Link OMIM 617599 to ORPHA:1934

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#181]
Dear all, 

A Spanish coder suggests linking [OMIM 617599](https://omim.org/entry/617599) to ORPHA:1934 [Early infantile epileptic encephalopathy](https://www.orpha.net/en/disease/detail/1934).

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

OMIM 617599 is already linked to ORPHA:1934 and it's visible on our website (see the file attached). 
![screenshot](https://github.com/OD4RD/Main-Help-Desk/assets/114141668/c93c8c7e-bbdf-4ca3-a6b8-b02736c49e27)


Let me know if you need another mapping. 

Best regards, 

Julie
