### ISSUE TITLE
ORPHA:317476 - Inheritance

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#183]
Dear all, 

Regarding ORPHA:317476 [X-linked immunodeficiency with magnesium defect, Epstein-Barr virus infection and neoplasia](https://www.orpha.net/en/disease/detail/317476), the OMIM phenotype [300853](https://omim.org/entry/300853) indicates that it is an **X-linked recessive** immunodeficiency.

Please, add this information on the Inheritance section of the disease page.

Kind regards, 

María Elena

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES , 

I will take care of the inheritance issue of this disease. 

Thank you for letting us know, 
Mickaël

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES , 

I changed the inheritance of ORPHA:317476 [X-linked immunodeficiency with magnesium defect, Epstein-Barr virus infection and neoplasia](https://www.orpha.net/en/disease/detail/317476) to X-linked recessive. It should be visible next week. 

Best regards, 
Mickaël
