### ISSUE TITLE
Trigeminal Trophic Syndrome

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#185]
Hi Marie Cecile:  We were recently contacted by a patient who has this condition. We also have a NORD report now. https://rarediseases.org/rare-diseases/trigeminal-trophic-syndrome/  It is added in MONDO  after my request: http://purl.obolibrary.org/obo/MONDO_0800478 

It seems to be a rare condition. I was wondering if you may consider adding it to Orphanet.

Please see:
Khan AU, Khachemoune A. Trigeminal trophic syndrome: an updated review. Int J Dermatol. 2019 May;58(5):530-537. https://pubmed.ncbi.nlm.nih.gov/29931799/ 

Thank you! Gioconda

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @galyea123,
Thank you for your message.
We will evaluate the creation of the ORPHA and inform you of the decision made following the medical and scientific committee meeting.
Best regards,
Marta

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @galyea123,

Based on current literature, Orphanet medical and scientific committee has validated the creation of "Trigeminal trophic syndrome" ORPHA:664901. 

Best regards,
Marta
