### ISSUE TITLE
Dates on ORPHAcodes and disease descriptions

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#189]
Dear All,

Is there any interest out there for the following:

1. A date for when an ORPHAcode was created.
2. A date for when the disease description was added. 

This has come up as an issue several times in Norway and we have posted a suggestion in RIC. Orphanet coordinating team is going to discuss it but we wonder if other countries have thoughts on this.

Kind regards,
Lene
Norway

**Comment by Orphanet-ES** [comment]
Thank you Lene for addressing this topic.
It would also be interesting to know when an ORPHA has been inactivated

Kind regards, 

María Elena

**Comment by LeneMartinsen** [comment]
Dear Marie-Cecile,
We wonder if you had the chance to bring this to discussion in the coordinating team yet?
We have had a few questions from professionals about this.
Norway also supports María Elenas addition of knowing the date for inactivation of a code.

Kind regards,
Lene

**Comment by MCecile-US14** [comment]
Dear @LeneMartinsen, dear @Orphanet-ES 

Apologies for the delayed answer. This request has been discussed by the Orphanet coordination (again).
Unfortunately it does not seems a reasonnable cost/benefit addition to display date of creation/inactivation or disease description' publication date in Orphanet website for the following reasons:

1. This is mostly an internal track data we do not specifically use it as in our system it gets updated each time we are modifying an ORPHAcode (e.g. Nomenclature or inactivation flag). But this can be retrieved using the **Orphanet Nomenclature differential file** from the [Nomenclature Pack](https://www.orphadata.com/pack-nomenclature/) where each year it is providing the resume of all new ORPHAcodes and all ORPHAcodes that are not available anymore (have been inactivated). 
2. Regarding the short description (definition), we have considered if releasing the update date would be useful, but in the end, we decided against it; definitions are part of the nomenclature, as for example the main name and the synonym of a disease. Once written, definitions are not updated regularly, as they contain the clinical description of a disease (its perimeter) that in theory is not changing during the years. Older definitions are as correct as newer ones, but putting a date would give a false information that the definition needs to be updated if it is too old.

Kind regards, 
Marie-Cécile

**Comment by LeneMartinsen** [comment]
Dear @MCecile-US14,
Thank you for discussing the issue again in the coordinating team. We understand the point of not showing the date of the disease summary as it stays mainly the same for many years and can be misunderstood as old.

I think the main thing with the date of the code is that if the professionals don't find the code in the coding file in the patient record but see it on www.orpha.net, they start wondering about the creation of that specific code. We do try to communicate as clearly as possible that it means it will most likely be included in the next update, but if the date was visible to the professional they might immediately understand (although, there is no guarantee for that of course). However, we also understand your point and the capacity of IT issues to explore and solve.

Thanks again! :)
Best,
Lene
