### ISSUE TITLE
Basal cell carcinoma of the oral mucosa

### ISSUE THREAD

**Issue by OrphanetDE** [OD4RD/Main-Help-Desk#190]
Dear all,

from an expert who wants to code : Basal cell carcinoma of the oral mucosa
Could you please consider to add this disorder to the database ?

please see also the following publication forwarded: 
[Basalzellkarzinom MSH.pdf](https://github.com/OD4RD/Main-Help-Desk/files/14603181/Basalzellkarzinom.MSH.pdf)
and also a reference to the PMID: 24202723 
https://pubmed.ncbi.nlm.nih.gov/24202723/

thanks and kind regards
Kathrin (Orphanet DE)

**Comment by MCecile-US14** [comment]
Dear @Mickael-Orphanet, 

Can you please evaluate this request when you have time? I am not sure it is to be considered (we do not create subtypes of carcinoma), to be look up with the Blue books classification. 

Thank you, 
Marie-Cécile

**Comment by OrphanetDE** [comment]
Dear Marie-Cécile, dear Mickael,
I think in this case it should be possible to add this entity, because the subtype "Basal cell carcinoma of vulva", OC 494451, is already included in the Orphanet nomenclature.
Kind regards,
Kurt (Orphanet DE)

**Comment by Mickael-Orphanet** [comment]
Dear @OrphanetDE , 

Based on current literature, Orphanet medical and scientific committee has validated the creation of ‘Intraoral basal cell carcinoma’, ORPHA:667678.  A rare basal cell carcinoma localized in the interior of the mouth detected with Ber-EP4 and Bcl-2 protein markers that differentiate from similar ressemblance in  baseloid squamous cell carcinoma, peripheral amenoblastoma and unique ondontogenic neoplasm. The carcinoma initiate in the gingiva with tumor arising from surface epithelium, scattered mitotic and apoptotic cells.  Patients could have some recurrences even after removal surgery.   The waiting time to see the disorder in Orphanet may take up to a week. 

Best regards, 
Mickael
