### ISSUE TITLE
craniofacial microsomia

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#191]
Hi Marie Cecile!     Orphanet has this as a key word for several conditions but does not include the term in the database.  All or some of the conditions with the key word link to OMIM craniofacial microsomia https://omim.org/entry/164210 which includes: 

HEMIFACIAL MICROSOMIA; HFM
OCULOAURICULOVERTEBRAL SPECTRUM; OAVS
GOLDENHAR SYNDROME
OCULOAURICULOVERTEBRAL DYSPLASIA
OAV DYSPLASIA
FACIOAURICULOVERTEBRAL SEQUENCE
FAV SEQUENCE

As per literature review: "Clinicians use several diagnostic terms for patients with underdevelopment of facial features arising from the embryonic first and second pharyngeal arches, including first and second branchial arch syndrome, otomandibular dysostosis, oculoauriculovertebral syndrome, and hemifacial microsomia. Craniofacial microsomia has become the preferred term. " https://pubmed.ncbi.nlm.nih.gov/30851752/  See also: https://pubmed.ncbi.nlm.nih.gov/34320587/

Thank you!  Best!, Gioconda Alyea

**Comment by MCecile-US14** [comment]
Dear @galyea123, 

Please note that due to the release of the Orphanet Nomenclature Pack 2024 (July 2024) and a high number of urgent requests to prioritize, this will be reviewed probably after summer break. 

Thank you for your understanding 
Kind Regards
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @galyea123, 

Indeed, after reviewing your request 'Craniofacial microsomia' is indeed a Keyword associated to 4 ORPHAcodes: 
ORPHA:374 'Goldenhar syndrome' deprecated and recognized as ORPHA:141132, OAVS
ORPHA:141136 'Otomandibular syndrome' deprecated and recognized as ORPHA:141132, OAVS
**[ORPHA:141132 ](https://www.orpha.net/en/disease/detail/141132?name=141132&mode=orpha) Oculo-auriculo-vertebral syndrome' (OAVS)** see Orphanet definition for full spectrum, cannot be resumed as 'craniofacial microsomia'
ORPHA:1131 X-linked mandibulofacial dysostosis
For now I removed the 'craniofacial microsomia' keyword from ORPHA:374 and ORPHA:141136 as it is misleading.

As you mentioned also, and as discussed in european guidelines cranio experts WG (PMID:32804824) the preferred term and clinical representation is being discussed while from Orphanet point of view it does not seems correct to rename OAV spectrum as a cranial malformation as the spectrum is wider than this, with associated features that are more complex than extra cranial.
Instead we are considering to group these disorders under the creation of a clinical group such as 'Craniofacial microsomia spectrum' with an associated description of the group, I am adding my colleague @Orphanet-EmilieGaillard, who will further follow up with this and can let you know if/when updates are done.
I am closing this ticket as finalized but feel free to post further comment if you wish (you will see get notifications) 

Kind Regards, 
Marie-Cécile

PS: I am taking this opportunity to let you know that I will be leaving Orphanet next week to move to another position in RD field. I would like to warmthly thank you to your contribution to RD knowledge and community, I really appreciated your suggestions  and to work together remotely with the same goal :)

**Comment by galyea123** [comment]
Dear Marie-Cécile, thank you for your detailed response.  While I feel a bit sad about you leaving Orphanet, I wish you the best in your new job and hope it brings you happiness! 
Warm regards,
Gioconda Alyea
