### ISSUE TITLE
Missing ORPHAcode combining Cleft lip and alveolus and Cleft lip/palate ?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#192]
Dear colleagues, 

We received the question below from a coordinator working in the "Centre labio-palatin" of the Cliniques Universitaires Saint-Luc (see: https://www.institutdesmaladiesrares.be/?q=node/14), which is a member of ITHACA.

"We noted the absence of a code combining "Cleft lip and alveolus" (ORPHA:141291) and "Cleft lip/palate" (ORPHA:199306). Does this mean that these are two distinct clinical entities and that a cleft combining lip-alveolar-palatal involvement must systematically be encoded by two distinct ORPHAcodes?

Also, when we encode “Fente labio-alvéolo-palatine” (in French) on ORPHANET, we are redirected to the term “Fente labio-palatine” (ORPHA199306) which is intriguing knowing that there is a term for “Fente labio-alvéolaire" (ORPHA:141291 ). Why is the entity “Fente labio-alvéolo-palatine” synonymous with “Fente labio-palatine” but not with “Fente labio-alvéolaire”?

In Orphanet, the following synonyms are listed for "Cleft lip/palate" (ORPHA:199306): "Alveolar cleft lip and palate", "Cleft lip and palate", "Cleft lip-alveolus-palate syndrome". However the perimeter of these different conditions is not exactly the same in terms of anatomical and morphological characteristics, extension and severity. Moreover experts involved in cleft management seem to be asking for a more precise nomenclature that makes it possible to code a cleft diagnosis involving lip-alveolo-palatal damage using a single ORPHAcode.

FYI, here is an interesting article related to the current challenges in the cleft classification systems:
doi: [10.1177/10556656211057368](https://doi.org/10.1177%2F10556656211057368)
PMCID: PMC9843539
PMID: [34812658](https://pubmed.ncbi.nlm.nih.gov/34812658)

Thanks in advance for your support regarding this issue. Kind regards,

Annabelle (Orphanet Belgium)

**Comment by Orphabe** [comment]
Please note that we already mentioned to the person who asked this question that it is not recommended to use 2 ORPHAcodes for a single diagnosis, referring to the section [3. Coding Recommendations · OD4RD/Main-Help-Desk Wiki], "Coding and using more than one ORPHAcode".

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 

Thank you for your messages.

- About the coding : agreed with the coding recommendations. 
Here it seems there is no confusion based on ORPHA:199306 and ORPHA:141291's short description (definition).
As ORPHA:199306 describe "Cleft lip and palate is a fissure type embryopathy extending across the **upper lip, nasal base, alveolar ridge and the hard and soft palate**"; This code does include both the alveolus and palate structures
**Then if experts want to code a cleft involving both the alveolar ridge/alveolus and palate regions they should use the code ORPHA:199306 'Cleft lip/palate'**.

- About the Nomenclature: indeed thanks to their remark there might a confusion based on the attribution of synonyms (translated in french also) and prefered terms for these entities. We will update the nomenclature accordingly and arrange the encoding part to be redirected to both entities based on the search term.
(NB: in french "Fente labio-alvéolo-palatine" is a correct synonym of "Fente labio-palatine" based on the perimeter defined and anatomy of the region from the lip to the palate (including the alveolus structure above the lip), and 'Fente labio-alévolaire' term does match with ORPHA:141291 (excluding the palate involvment as stated in the definition)). 

Please note we are currently in touch with ERN CRANIO experts (see https://github.com/OD4RD/Main-Help-Desk/wiki/8.-Orphanet%E2%80%90ERN-collaborations) to create the 'combined form of soft and hard cleft palate' missing in our Group of Disorders ORPHA:2014 'Cleft palate' (request came from a German RD experts center in 2023).
I will ask confirmation to these experts that we are not missing any entity here and gave them the opportunity to check the disease perimeters/naming of these entities.

Hope it helps and thank you for the valuable experts feedbacks
Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 

Is this more clear? I did not any expert' answer about this from my side
If so, I will close this ticket 
Kind Regards, 
Marie-Cécile

**Comment by Orphabe** [comment]
Dear Marie-Cécile,

I sent your response to the people concerned on March 26, as well as the link to this GitHub post. I invited them to send us any comments or questions on this subject, but I have not received any new messages since. So I guess we can close this ticket (even if it means reopening it later if necessary).

Kind regards,

Annabelle

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 

FYI, we have a planned meeting with ERN CRANIO experts about this Group of disorders, ORPHA:1991 in September. I will use the opportunity to confirm with them the coding request you raised here and keep you update if any update are made to this group of ORPHAcodes.

Kind Regards
Marie-Cécile

**Comment by Orphabe** [comment]
Thank you very much, Marie-Cécile! 

I transferred the information to the clinicians who made the request.

Kind regards,

Annabelle (Orphanet Belgium)
