### ISSUE TITLE
Use of typology in HIS

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#194]
Dear All,

In the process of making a new solution for implementing the ORPPHAcodes in the electronic health record at Oslo Univ Hospital,
a question about whether to include the typology in the health information records has come up (i.e. the different categories Disease, Clinical syndrome, Malformation syndrome, Biological anomaly, Morphological anomaly etc.).

Our question to you is whether anyone have thoughts or experience with this, and whether Orphanet has any plans to change the use of typology in the future? Personally, I always thought that some of the categories are difficult to understand - e.g. the actual difference between disorder and disease.

We lean towards not including typology because we think there will be too many details for the professionals, but we could perhaps have a solution where tyoplogy is hidden and could be used for statistics if necessary.

The reason the question has come up is because the IT company working with us are very thorough and have dived deep into the nomenclature files, Orphanet, and the field of rare disorders in general.

Kind regards,
Lene

**Comment by MCecile-US14** [comment]
Dear @LeneMartinsen, 

Thank you for your comment regarding the usage and addition of the Orphanet typology in the norwegian EHR.
This question has been raised in the past and the proposition was declined; the typology used to qualify ORPHAcode is meant to be an internal usage and quality control.
This is a criteria applied when an ORPHAcode is newly created and it can be part of Nomenclature modifications that are only tracked internally for internal needs and quality control (you can consult it only in the internal tools, in the Orphanet nomenclature procedure and it can be mentioned in the disease meeting report eventually). 
Orphanet has no plan to change the use of the typology in the future
As you said, the typology is quiet specific and sometimes hard to navigate even for RD experts; Orphanet does not recommend to not include the typology of ORPHAcodes in HIS/EHR.

Kind Regards, 
Marie-Cécile
