### ISSUE TITLE
Correction Request

### ISSUE THREAD

**Issue by CMR3388** [OD4RD/Main-Help-Desk#196]
Hello,

I would like to request a content revision for the Hereditary diffuse leukoencephalopathy with axonal spheroids and pigmented glia page: https://www.orpha.net/en/disease/detail/313808. 
 
1. This name has been updated to Adult-onset leukoencephalopathy with axonal spheroids and pigmented glia and should ideally be the main title where information is found. 
2. The ICD-10 code on the website is incorrect. The correct one is ICD-10: G93.44. 
3. The description of the disease is lacking key information. Ideally, it would state that:
-  Adult-onset leukoencephalopathy with axonal spheroids and pigmented glia (ALSP) was previously known to be 2 neurodegenerative disorders: hereditary diffuse leukoencephalopathy with spheroids and familial pigmentary orthochromatic leukodystrophy. 
- ALSP is rare, progressive neurological disease that causes white matter abnormalities in the brain. Lesions of this white matter lead to major changes in personality, thinking (cognition), and muscle function, eventually causing people with this disorder to develop dementia and later decline into a vegetative state.
- ALSP is a disease caused by a rare mutation in the CSF1R gene on chromosome 5. It is an autosomal dominant disease, meaning that each child born to someone who has the CSF1R gene mutation has a 50% chance of also having this mutation.
- Symptoms of ALSP overlap with frontotemporal dementia and other disorders associated with dementia such as Alzheimer disease as well as other neurological disorders such as Parkinson’s disease, multiple sclerosis, schizophrenia and several others, making diagnosis difficult unless genetic testing is done. 
- On average symptoms first appear around age 43 but may appear in the age range of 18-78 years old.

Resources: 
https://pubmed.ncbi.nlm.nih.gov/29122458/
https://pubmed.ncbi.nlm.nih.gov/35185751/
https://pubmed.ncbi.nlm.nih.gov/37839910/
https://sistershopefoundation.org/
https://www.alspinfo.com/

Thank you for your consideration,
Rubio

**Comment by JTorphanet** [comment]
Dear @CMR3388, 

Thank you for your message and valuable contribution. 

Indeed, I have reviewed your request and the current main term is no longer used. I have just done the modification and it will be visible next week on our website. Moreover, I have also modified the ICD-10 code as you raised; this entity was wrongly aligned. 

I have transmitted the other points to @Orphanet-AysegulSenol, the project manager in charge of definitions writing.  

Thank you very much, 
Best regards, 

Julie

**Comment by CMR3388** [comment]
Hi Julie!

Thank you so much for your email. This is great news! Up to date information is a priority for the community and I thank you for your help.

Have a great day!

Clarissa

**Comment by CMR3388** [comment]
Good morning,

I have been trying to check the website update and every time I try, there is no longer a page. Does this mean it is being reviewed?

Thank you in advance!

Clarissa

**Comment by CMR3388** [comment]
Dear @Orphanet-AysegulSenol,

I have been trying to check the website update and every time I try, there is no longer a page. Does this mean it is being reviewed?

Thank you in advance!

Clarissa
