### ISSUE TITLE
If an entity in the ORPHA nomenclature is classified as „moved to…“ are we allowed to still use the ORPHAcode of this entity?

### ISSUE THREAD

**Issue by OrphanetDE** [OD4RD/Main-Help-Desk#20]
If an entity in the ORPHA nomenclature is classified as „moved to…“ are we allowed to still use the ORPHAcode of this entity?

**Comment by MCecile-US14** [comment]
If an entity has been deprecated it means there was an evolution of scientific knowledge (based on recent literature) and Orphanet assessed that the current representation is no longer accurate and a disease initially recognized independently is now described as part of another disease. Thus, the corresponding ORPHAcode has been inactivated and a relationship “moved to” is applied toward the target entity. The deprecated code should not be used anymore and the target ORPHAcode is the one recommended to use.

Of note: on orpha.net, for deprecated entities you will find a text informing the users that the entity has been excluded from the Orphanet nomenclature and has been moved to a new code.

Please use the Wiki page for official answers on this topic: https://github.com/OD4RD/Main-Help-Desk/wiki/ORPHAcodes#if-an-entity-in-the-orpha-nomenclature-is-classified-as-moved-to-are-we-allowed-to-still-use-the-orphacode-of-this-entity
