### ISSUE TITLE
Noxacusis

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#208]
Request to consider adding a term. 
We were contacted by a patient organization asking to add Noxacusis or Pain Hyperacusis to the rare diseases list

Synonyms
Noxacusis
Pain Hyperacusis
Noise-Induced Pain
Auditory Nociception

Parent term 
Hyperacusis

Definition
Noxacusis/Pain Hyperacusis is characterized by individuals who experience otalgia or pain (e.g., dull ache, burning, sharp, stabbing pain and throbbing pain) in response to everyday sounds. This differs clinically from those whose primary symptom is the perception of everyday sounds as excessively loud (termed loudness hyperacusis).

https://pubmed.ncbi.nlm.nih.gov/25104073/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4664349/

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4348215/
https://pubmed.ncbi.nlm.nih.gov/36395696/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5928178/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8446270/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10899329/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4664349/

See also: https://hyperacusiscentral.org/insights-into-auditory-nociception-an-interview-with-dr-jaime-garcia-anoveros/  https://rarediseases.info.nih.gov/diseases/9655/hyperacusis

Thank you, Gioconda Alyea

**Comment by MCecile-US14** [comment]
Dear @galyea123, 

Thank you for your request. We already have been contacted by Ana Raab earlier this year to ask whether we could consider the inclusion of 'Noxacusis/pain hyperacusis' after your recommandations and we replied to her the following elements.
Despite it has recently been included in MONDO, and as you know we have different inclusion criteria as we evaluate each request based on 3 criteria to create a new ORPHAcode: a clinical entity must present an homogeneous and descriptable phenotype, minimum 2 published cases and a prevalence under the treshold 1/2000 (related to the European regulation on orphan medicinal products). 

Based on the medical and scientific literature, at the moment, Orphanet wont add 'Noxacusis/pain hyperacusis' in our database for 2 main reasons: 
- the rarity is not established.  According to PMID:36395696 (2022), the prevalence in children and adolescents is between 3,2% and 17,1%.  
- It seems that noxacusis/pain hyperacusis is more described as a phenotypic entity/clinical sign and not a disorder _per se_. 

Please, do not hesitate to come back to us if you have any relevant data about the prevalence proving the rarity and we will re-evaluate your request. 

Kind regards, 
Marie-Cécile

**Comment by galyea123** [comment]
Hi   Marie-Cécile!  Thank you so much for your prompt and detailed response. 

The 3,2% and 17,1%. prevalence refers to hyperacusis which is the "parent" term and it is not rare. I did not find a report with a specific prevalence for noxacusis but I wanted to tell you that I did send a message to a doctor who has experience working with affected patients and who have written some articles. 
I do believe that  noxacusis/pain hyperacusis has specific features and pathologic mechanisms that can allow to consider it as a clinical condition per se. Please see the articles I mentioned in my first message that describe the pathology of the condition.

I probably will reach out to you again when I hear back from the doctor as he may have some more information.

Thank you again!!

Gioconda
