### ISSUE TITLE
OMIM 159000 moved to 609200

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#209]
Dear all, 

Regarding the OMIM [159000](https://omim.org/entry/159000), it has been moved to [609200](https://omim.org/entry/609200), however in Orphanet it's still linked to the ORPHA:266 [Autosomal dominant limb-girdle muscular dystrophy type 1A](https://www.orpha.net/en/disease/detail/266).

This ORPHA also has the active OMIM linked, therefore, could you delete the discarded OMIM code?

Kind regards,

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Thank you for your message. Indeed, the OMIM has been moved and I see that the OMIM link is redirecting to the new OMIM, so there is no possible confusion, this will be updated and removed in Orphanet as soon as possible.
Please note that as the Nomenclature/Alignement manager position is currently under recruitment; meanwhile we will treat the minimim urgent requests regarding alignement with others terminologies until a new manager can take over.

Thank you for your understanding, 
Kind Regards, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14,

I would like to remind you that OMIM 159000 is still linked to ORPHA:266, although it has been inactivated and replaced by another active OMIM code.

Kind regards, 

María Elena

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES , 

OMIM 15900 as been unlinked of OPRHA:266. I am actually reviewing for the next months the issue related also to [https://github.com/OD4RD/Main-Help-Desk/issues/212](https://github.com/OD4RD/Main-Help-Desk/issues/212 ). Please note that the OMIM will not be visible until next week. 

Best regards,
Mickael
