### ISSUE TITLE
Creation of an ORPHAcode for neurodevelopmental disorder with hypotonia, dysmorphic facies, and skin abnormalities (NEDHFS)?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#210]
Dear colleagues,

We were questioned by the physician in charge of the neonatal screening centre at Cliniques Universitaires Saint-Luc about a clinical entity missing from the Orphanet nomenclature. He is also a member of the team attached to MetabERN within these clinics.

He proposes the **creation of an ORPHAcode for a medical condition associated with a mutation in the PGM2L1 gene**. It is a neurodevelopmental disorder characterized by hypotonia, dysmorphic facies, skin abnormalities, severe global developmental delay with impaired intellectual development and poor or absent speech. 

References:
-  Article: Morava, E., Schatz, U. A., Torring, P. M., Abbott, M. A., Baumann, M., Brasch-Andersen, C., Chevalier, N., Dunkhase-Heinl, U., Fleger, M., Haack, T. B., Nelson, S., Potelle, S., Radenkovic, S., Bommer, G. T., Van Schaftingen, E., & Veiga-da-Cunha, M. (2021). Impaired glucose-1,6-biphosphate production due to bi-allelic PGM2L1 mutations is associated with a neurodevelopmental disorder. American journal of human genetics, 108(6), 1151–1160. [https://doi.org/10.1016/j.ajhg.2021.04.017]
- OMIM: https://omim.org/entry/620191 

I explained that Orphanet does not create ORPHAcodes for "non-specific" phenotypes and that this request must be carefully analyzed based on a decision diagram developed by Orphanet to decide whether syndromic entities are considered specific or not. Could you please therefore assess this request? Does it warrant the creation of a new ORPHAcode or should this condition be coded using the ORPHAcode for “Non-specific syndromic intellectual disability” (ORPHA:528084)?

Thanks for your support, kind regards,

Annabelle (Orphanet Belgium)

**Comment by Mickael-Orphanet** [comment]
Dear @Orphabe, 

Orphanet medical and scientific committee decided to not create PGM2L1 deficiency. There is no homogenous phenotype with the 4 patients to create a specific entity. The only specific feature is keratosis pilaris that is not well seen in the paper. Do not hesitate to contact us if supplementary information could be considered or to inform us about new publications in order to re-evaluate the decision. 
However, we linked PGM2L1 to Non-specific syndromic intellectual disability (ORPHA:528084). The link should be visible. 

Best regards,
Mickael

**Comment by Orphabe** [comment]
Dear Mickael,

Thank you very much for considering this proposal. The decision was communicated to the expert who made the request. 

I confirm that the link between _PGM2L1_ and "Non-specific syndromic intellectual disability" (ORPHA:528084) is visible on the Orphanet website.

Kind regards,

Annabelle (Orphanet Belgium)
