### ISSUE TITLE
New ORPHA: OMIM 619125 Kaya-Barakat-Masson syndrome

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#213]
Dear all, 

At the request of a Spanish coder, I propose the creation of a new ORPHA code for the OMIM [619125 ](https://omim.org/entry/619125)Kaya-Barakat-Masson syndrome, a severe autosomal recessive neurodevelopmental disorder caused by homozygous or compound heterozygous mutation in the YIF1B gene ([619109](https://omim.org/entry/619109)) on chromosome 19q13.

In Orphanet, this OMIM and the gene are linked to ORPHA:528084 [Non-specific syndromic intellectual disability](https://www.orpha.net/en/disease/detail/528084).

Kind regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Other references provided by the expert:

https://www.ncbi.nlm.nih.gov/medgen/1725501
https://pubmed.ncbi.nlm.nih.gov/36948290/

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES, 

Based on current literature , Orphanet medical and scientific committee has validated the creation of ‘Neurodevelopmental disorder-spasticity-movement disorder-epileptic syndrome’, ORPHA:684240. Neurodevelopmental disorder that show developmental delay, brain abnormalities with microcephaly.Petients present a progressive encephalopathy with various degrees of movement disorder, microcephaly, epilepsy and visual impairment (like nystagmus and strabismus). Brain abnormalities are also observed in patients with white matter abnomalities, cerebellar hypoplasia, corpus callosum hypoplasia and parenchymal volume loss. 
I have linked YIF1B to this entity as disease-causing germline mutation. 
Please wait a week to see it in the Orphanet website. 

Best regards, 
Mickael

**Comment by Orphanet-ES** [comment]
Dear @Mickael-Orphanet ,

Thanks for your help.
Next week I will check this information, translate it into Spanish and report back to the expert.

Best regards, 

María Elena
