### ISSUE TITLE
New disorder: neurooculocardiogenitourinary syndrome (NOCGUS)

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#215]
Dear all, 

A Spanish coder suggests the creation of a specific ORPHAcode for neurooculocardiogenitourinary syndrome (NOCGUS), a multisystem disorder characterized by poor growth and anomalies of the ocular, craniofacial, neurologic, cardiovascular, genitourinary, skeletal, and gastrointestinal systems.
NOCGUS is caused by heterozygous mutation in the WDR37 gene ([618586](https://omim.org/entry/618586)) on chromosome 10p15.

These are the references that he has provided me:
https://omim.org/entry/618652
https://www.sciencedirect.com/science/article/abs/pii/S0387760423001778
https://onlinelibrary.wiley.com/doi/full/10.1002/ajmg.a.62020

Kind regards, 

María Elena

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @Orphanet-ES,
Thank you for your message.
We will evaluate the creation of the ORPHAcode and inform you of the decision following the Medical and Scientific Committee meeting.
Best regards,
Marta

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @Orphanet-ES,

Based on current literature, Orphanet medical and scientific committee has validated the creation of 'NOCGUS syndrome, ORPHA:684305'. The code is already available on the Orphanet website. More information on the classification and the summary of the disease will be available as soon as possible.

Kind regards,
Marta

**Comment by Orphanet-ES** [comment]
Dear @Orphanet-MartaFructuoso 

Thanks for your help.
I have already translated the name of the disease and will inform the expert once the translation is displayed on the website.

Kind regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Dear @Orphanet-MartaFructuoso ,

Please, add the OMIM [618652](https://omim.org/entry/618652) to this ORPHA.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear Maria Elena, 

Thank you for your comment, as mentioned in the Orphanet disease meeting decision workflow, OMIM# are alignments annotations therefore they are applied by another nomenclature manager (after curation analysis) and subsequently to the creation of the ORPHAcode. (e.g. same for gene linkage, ICD-10 code, epidemiology data, HPO etc...)
This will be achieved in a second time, and it may take extra time because the new alignment nomenclature manager is starting in September.
Please do not reopen a ticket for this and newly creation.

Kind Regards, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear @Seed-Orphanet,

The OMIM [618652](https://omim.org/entry/618652) has not been added yet to the ORPHA:684305.

Could you add it?

Kind regards, 

María Elena

**Comment by Seed-Orphanet** [comment]
Dear @Orphanet-ES 
I will tag @Mickael-Orphanet, as he is the one in charge of the OMIM alignments because they are closely related to the gene activity (for all the other alignments it's me 😃)
Kind regards,
Seed

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES,  
The OMIM as already been added months ago, we just notice that it actually do not appear on the website but if you look for the OMIM in the search disease bar it will give you a result. We are working with the IT team to resolve this display issue as soon as possible. 

Best regards, 
Mickael

**Comment by Orphanet-ES** [comment]
Dear @Mickael-Orphanet,

Thanks for the information.
There are several new diseases that are in the same situation, so I hope you can solve it soon.

Best regards, 

María Elena
