### ISSUE TITLE
Age of onset of ORPHA:412057

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#218]
Dear all, 

A Spanish expert suggests correcting the age of onset of ORPHA:412057 [Autosomal recessive cerebellar ataxia due to STUB1 deficiency](https://www.orpha.net/en/disease/detail/412057?name=412057) according to the following description from OMIM [615768](https://omim.org/entry/615768):
"_Most patients have onset in the teenage years, although earlier and later onset have been reported_".

This would also match the assigned ICD-10: [G11.1 Early-onset cerebellar ataxia](https://icd.who.int/browse10/2019/en#/G11.1) 

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @moi-epiUS14, 

Can you please look into this and update the age of onset as suggested?
Thank you
Marie-Cécile

**Comment by moi-epiUS14** [comment]
Hello all, 

Thank you for your contribution, I modified the age of onset for this entity. 

However, next time, please cite a PMID or a link to the information source. 
It makes it easier for us to verify the information, and come back to you quickly. 

Best,
M

**Comment by Orphanet-ES** [comment]
Thanks Moi,

We will take into account your recommendation and I will cite a PMID to facilitate your work.
I thought that the OMIM reference was enough. Sorry for the inconvenience.

Best regards,

María Elena
