### ISSUE TITLE
New ORPHAcode for Combined oxidative phosphorylation deficiency 54 

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#220]
Dear all,

A Spanish coder suggests the creation of an ORPHAcode for Combined oxidative phosphorylation deficiency 54, caused by homozygous or compound heterozygous mutation in the PRORP gene ([609947](https://omim.org/entry/609947)) on chromosome 14q13.

OMIM  [619737 ](https://omim.org/entry/619737)

Kind regards, 

María Elena

**Comment by Orphanet-AysegulSenol** [comment]
Dear Maria Elena, 

I will treat this demand in September and keep you updated, 

Best wishes, 

Aysegul

**Comment by Orphanet-ES** [comment]
Dear @Orphanet-AysegulSenol ,

Is there any news?

Kind regards, 

María Elena

**Comment by Orphanet-AysegulSenol** [comment]
Dear Maria Elena, 

I am sorry that I couldn't reply before. Indeed I have news on this subject: It has been decided not to create this entity. However the gene (PRORP) and the OMIM 619737 will be added to ORPHA: 2855 Perrault syndrome. These actions will be taken in 2 weeks of time thus not visible for now at the website. 

Best wishes, 

Aysegul
