### ISSUE TITLE
ORPHA:1037: correct link to ICD-11

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#222]
Dear all, 

Regarding ORPHA:1037 [Arthrogryposis multiplex congenita](https://www.orpha.net/en/disease/detail/1037), the link to ICD-11 is incorrect.

The ICD-11 code "LD26.41" links to https://icd.who.int/browse/2024-01/mms/en#1300118676 (DB98.5 Budd-Chiari syndrome)
instead of https://icd.who.int/browse/2024-01/mms/en#1930990330 (LD26.41 Arthrogryposis multiplex congenita).

Kind regards, 

María Elena

**Comment by caterina-lucano-orphanet** [comment]
Dear María Elena,
thank you for your suggestion, there was indeed an error in the link.
I have corrected it, and it will be visible on the website next Monday.

Kind regards,
Caterina
