### ISSUE TITLE
new disease : Adenoid Ameloblastoma

### ISSUE THREAD

**Issue by OrphanetDE** [OD4RD/Main-Help-Desk#224]
Dear all,

an enquiry from a german coder: could you please consider to add <Adenoid Ameloblastoma> to the nomenclature.
It was recently included as new entity in the 5th edition of the World Health Organization (WHO) Classification of Head and Neck Tumors. please see https://pubmed.ncbi.nlm.nih.gov/35578902/ 
The World Health Organization Classification of Odontogenic Lesions: A Summary of the Changes of the 2022 (5th) Edition

Further Literature: 
PMID: 37540485: A Systematic Review of Adenoid Ameloblastoma: A Newly Recognized Entity
PMID: 35840721 Adenoid ameloblastoma harbors beta-catenin mutations

kind regards,
Kathrin

**Comment by MCecile-US14** [comment]
Dear @OrphanetDE, 

Thank you for your request, as mentioned in others requests this will be evaluated in the coming months by the Orphanet scientific and medical committee (within 6months). We will come back to you with any decision taken.
Kind Regards, 
The Orphanet Nomenclature team

**Comment by Mickael-Orphanet** [comment]
Dear @OrphanetDE, 
Based on current literature, Orphanet medical and scientific committee has validated the creation of ‘Adenoid ameloblastoma’, ORPHA:689430. A rare odontogenic tumor that is benign, defined by an epithelial odontogenic neoplasm composed of cribiform architecture and duct-like structures and frequently including dentinoid. It is usually painless. The diagnostic is made by the presence of ameloblastoma-like component, duct-like structure, whorls/morules, cribiform architecture. This odontogenic tumour may exhibit the histological features of both ameloblastoma and adenomatoid odontogenic tumour. The rarity has been established.   

Best regards, 
Mickael

**Comment by OrphanetDE** [comment]
Dear Mickael,

thanks for the update on creation of ORPHA:689430 !

Kind regards,
Kathrin

Von: Mickael-Orphanet ***@***.***>
Gesendet: Montag, 18. November 2024 10:02
An: OD4RD/Main-Help-Desk ***@***.***>
Cc: orphanet ***@***.***>; Mention ***@***.***>
Betreff: Re: [OD4RD/Main-Help-Desk] new disease : Adenoid Ameloblastoma (Issue #224)


Dear @OrphanetDE<https://github.com/OrphanetDE>,
Based on current literature, Orphanet medical and scientific committee has validated the creation of ‘Adenoid ameloblastoma’, ORPHA:689430. A rare odontogenic tumor that is benign, defined by an epithelial odontogenic neoplasm composed of cribiform architecture and duct-like structures and frequently including dentinoid. It is usually painless. The diagnostic is made by the presence of ameloblastoma-like component, duct-like structure, whorls/morules, cribiform architecture. This odontogenic tumour may exhibit the histological features of both ameloblastoma and adenomatoid odontogenic tumour. The rarity has been established.  

Best regards,
Mickael
