### ISSUE TITLE
Text contributions from professionals on rare epilepsy

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#225]
Dear Orphanet,

We have experts in our National Advisory Unit On Rare Disorders working on rare epilepsies. They would like to contribute to disease summaries for the disorders where they have expertise. Would it be possible to give them the direct contact info to a person in Orphanet working on medical texts? 

The name of the expert centre (registered in Orphanet): 
NK-SE - Nasjonalt kompetansesenter for sjeldne epilepsirelaterte diagnoser (NO)
NK-SE - National Centre for Rare Epilepsy-Related Disorders (ENG)
This is the official expert centre on rare epilepsies in Norway and I can guarantee for their quality.
The names and e-mails to the professionals:
Aina Ljosåk Hansen, ainhan@ous-hf.no
Silje Systad, sisyst@ous-hf.no

Kind regards,
Lene

**Comment by Orphanet-MartaFructuoso** [comment]
Dear Lene,
Thank you for your message.
We are very pleased to hear that the experts are interested in contributing! I have already put you in touch with the people who are concerned about this.
Kind regards,
Marta
