### ISSUE TITLE
ICD-10 linked to ORPHA:3454 Intellectual disability-developmental delay-contractures syndrome

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#226]
Dear all, 

I am contacting you regarding the ICD-10 assigned to ORPHA:3454 [Intellectual disability-developmental delay-contractures syndrome](https://www.orpha.net/en/disease/detail/3454).
ICD-10: [G71.8 ](https://icd.who.int/browse10/2019/en#/G71.8) Other primary disorders of muscles

According to its clinical description: "The syndrome is characterized by an association of **arthrogryposis multiplexa congenita** and intellectual disability. Affected patients are born with severe contractures (arthrogryposis) and muscle weakness causing respiratory distress. Intellectual disability and delayed motor development are found in all patients. Facial weakness (ptosis) and bulbar weakness (feeding difficulty), characteristic dysmorphic facial features (possibly including long flat philtrum, low-set ears, high-arched palate, and carp-shaped mouth), and skeletal abnormalities (camptodactyly, hip dislocation, scoliosis, kyphosis, lordosis and pes equinovarus) have been reported. Other neurological signs may include spasticity and seizures. Heterozygous female carriers may also be affected, but to a lesser degree (intellectual disability, distal muscle weakness, camptodactyly, joint contractures, and pes equinovarus).". 

As you can see, the first characteristic is that it presents arthrogryposis multiplexa congenita, and this would be excluded if we review the ICD-10 assigned to a higher level.
[G71](https://icd.who.int/browse10/2019/en#/G71) Primary disorders of muscles
Excl.:
    arthrogryposis multiplex congenita ([Q74.3](https://icd.who.int/browse10/2019/en#/Q74.3)) 
    metabolic disorders ([E70-E90](https://icd.who.int/browse10/2019/en#/E70)) 
    myositis ([M60.-](https://icd.who.int/browse10/2019/en#/M60))

Taking into account the description included in Orphanet and in OMIM [314580](https://omim.org/entry/314580), a Spanish coder suggests the ICD-10 [Q87.8](https://icd.who.int/browse10/2019/en#/Q87.8) Other specified congenital malformation syndromes, not elsewhere classified

He believes that it would fit better since this syndrome is a "congenital malformation syndrome affecting multiple systems".

Thank you in advance for studying this proposal.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
see #53

**Comment by Seed-Orphanet** [comment]
Dear @Orphanet-ES 
the ICD-10 alignment was indeed not correct, and the suggested Q87.7 is the best fit. I have made the corrrection (it will appear on the Orphanet website on Monday).
Thank you for flagging this to us!
Kind regards,
Seed

**Comment by Orphanet-ES** [comment]
Dear @Seed-Orphanet ,

It seems that you have mistakenly assigned the code Q87.7, which does not exist as far as I know.
The good one is [Q87.8](https://icd.who.int/browse10/2019/en#/Q87.8) Other specified congenital malformation syndromes, not elsewhere classified.

Kind regards, 

María Elena

**Comment by Seed-Orphanet** [comment]
Dear @Orphanet-ES 
I mistyped here and copied the wrong code, thank you for signaling this, I will make the correction.
Kind regards,
Seed

**Comment by Seed-Orphanet** [comment]
Dear @Orphanet-ES 
the correct Q87.8 ICD-10 code will appear on the website on Monday.
Have a nice weekend!
Kind regards,
Seed

**Comment by Orphanet-ES** [comment]
Dear @Seed-Orphanet ,

Thanks for your help.

The ICD-10 code is correct now.

Kind regards, 

María Elena
