### ISSUE TITLE
new disorder: Splenic hemangioma

### ISSUE THREAD

**Issue by OrphanetDE** [OD4RD/Main-Help-Desk#229]
Dear all,

for a coder in Germany, could you please consider to add Splenic hemangioma to the database. 

Reference: PMID: 12945936 Splenic vascular tumors
You will find section related to Splenic hemangioma here. 

Please tell me if you need further information.
kind regards,
Kathrin

**Comment by MCecile-US14** [comment]
Dear @Orphanet-MartaFructuoso, 

Can you look into this along with your collaboration with VASCERN
Thank you
Marie-Cécile

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @OrphanetDE ,
Thank you for your message.
We will evaluate the creation of the ORPHAcode and inform you of the decision following the medical and scientific committee meeting in September 2024.
Best regards,
Marta

**Comment by OrphanetDE** [comment]
Dear Marta, 
I have reopened this ticket as no decision has yet been made.. 
Thanks, Kathrin

**Comment by Orphanet-MartaFructuoso** [comment]
Dear Kathrin,
The issue has recently been discussed with our expert from the VASCA working group (ERN-VASCERN). The creation of the ORPHAcode will be presented at our next Medical and Scientific Committee meeting after the summer break.
I will write back to you in September with the decision.
Kind regards,
Marta

**Comment by Orphanet-MartaFructuoso** [comment]
Dear Kathrin,
‘Splenic venous malformation, ORPHA: 688523’ has been created as a disorder. The main term is in accordance with ISSVA nomenclature, proposed and validated by ERN-VASCERN experts. Although ubiquitous in the literature and most familiar to many clinicians, the term "hemangioma" is outdated and not suitable to name this vascular anomaly. However, for consistency with the majority of the existing literature "Splenic hemangioma" has been kept as a synonym.
Best regards,
Marta
