### ISSUE TITLE
Online courses

### ISSUE THREAD

**Issue by OD4RDFIN** [OD4RD/Main-Help-Desk#23]
Are there any online courses on ORPHA codes?

**Comment by MCecile-US14** [comment]
Existing material (presentations, videos and audio) is available to all specific Orphanet members of the Orphanet network. 
There are no online courses/MOOC available at the moment for the general public.

However, short informative videos and tutorials that can help with content dissemination to the general public are available on Youtube:
1. Quick and general videos tutorials on Orphanet nomenclature, how to search a gene/disease using Orphanet (FR-EN) and **ORPHAcodes** (**EN-IT-SP-RO-DE-FR-CS now FI and NL**) [Orphanet and Orphacodes short videos (https://www.youtube.com/channel/UCKMLSL9hlrxz6zKFod5IlnA/videos).
2. As an exemple of content, French EJP RD webinars: [EJP-RD webinars fr] (https://www.youtube.com/playlist?list=PLdOp3b6E1DxZMArTfsX_EwTHmfFqNPrZu)

Hope this can help, 
Kind Regards, 
Marie-Cécile
