### ISSUE TITLE
Data transfer agreement for translating disease summaries to Norwegian

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#230]
Dear Orphanet,

The rare epilepsy expert centre in Norway would like to translate and use some of the Orphanet disease summaries on their own website. Is that possible? If yes, I assume they need to sign a data transfer agreement? How do we move forward with this?

This is the same expert centre as in #225:
NK-SE - Nasjonalt kompetansesenter for sjeldne epilepsirelaterte diagnoser (NO)
NK-SE - National Centre for Rare Epilepsy-Related Disorders (ENG)

The names and e-mails to the professionals:
Aina Ljosåk Hansen, ainhan@ous-hf.no
Silje Systad, sisyst@ous-hf.no

Kind regards,
Lene

**Comment by MCecile-US14** [comment]
Dear @LeneMartinsen, 

Yes it is possible, indeed they need to sign up a _Data Transfer Agreement_ 
For this type of request I invite you to transfer this contact email **partnerships.orphanet@inserm.fr** to the teams or experts interested by this activity and they will receive the corresponding informations.

Kind regards
Marie-Cécile
