### ISSUE TITLE
Arrhinia-choanal atresia-microphthalmia syndrome ORPHA:1135 and Hyposmia-nasal and ocular hypoplasia-hypogonadotropic hypogonadism syndrome ORPHA:2250

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#232]
To MCecile:

Hi!  I believe that these two entities, "Arrhinia-choanal atresia-microphthalmia syndrome" ORPHA:1135 and "Hyposmia-nasal and ocular hypoplasia-hypogonadotropic hypogonadism syndrome" ORPHA:2250 are the same, as some individuals do not have a complete absence of the nose.  

Note that both are linked to the same OMIM ID and that Orphanet states that "Hyposmia-nasal and ocular hypoplasia-hypogonadotropic hypogonadism syndrome" (last updated in 2009) is a synonym with "Bosma arhinia-microphthalmia syndrome", which is https://omim.org/entry/60345 . 

For the Arrhinia-choanal atresia-microphthalmia syndrome I was not able to find any pubmed references specific to this entity. 

Please see also MedlinePlus: https://medlineplus.gov/genetics/condition/bosma-arhinia-microphthalmia-syndrome/#synonyms

Thank you, Gioconda Alyea

**Comment by Mickael-Orphanet** [comment]
Dear @galyea123, 

Based on current literature, the Orphanet medical and scientific committee has decided to exclude "Arrhinia-choanal atresia-microphthalmia syndrome" (ORPHA:1135) from the nomenclature. This entity, initially described as an independent diagnosis, has now been incorporated into "Hyposmia-nasal and ocular hypoplasia-hypogonadotropic hypogonadism syndrome" (ORPHA:2250).

The former designation was based on publications by Thiele et al. (1996) and Ruprecht and Majewski (1978), which described patients with arrhinia, microphthalmia, and choanal atresia. Subsequent research revealed that other clinical features such as hernias and hypogonadism could also be observed in patients with Bosma syndrome (described in 1981). It is now recognized that these conditions are part of the same syndrome, and they are cited in studies on Bosma syndrome (PMID:28067909). A review in Pediatrics and Neonatal Disorders also clearly stated this (Rashmi N, Thotambailu A, Prakash BG, Malini B, Babu AR (2020) Bosma Syndrome "Mimic" in a Young Infant - Case Report and Literature Review)

Best regards, 
Mickael
