### ISSUE TITLE
How to obtain mapping files between ORPHAcodes and SNOMED IDs by medical classification/groups of interests?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#242]
Dear colleagues,

As you might know, in Belgium, the use of SNOMED CT will soon become mandatory in the electronic patient files. This explains why our clinicians and coders are particularly in demand for tools to have easy access to ORPHAcodes and corresponding SNOMED identifiers. 

We of course present the SNOMED CT-Orphanet nomenclature map available via Orphadata. However, experts would like to have access, not to the entire rare disease nomenclature, but to mappings sorted by groups of interest (for example, having the ORPHAcodes-SNOMED IDs mapping only for the PIDs group). 

To my knowledge, this is not possible to provide customized Excel files which would give the mapping between ORPHAcodes and SNOMED ID by classification or groups of interest. This is something we can do, using Arbor, for matching with ICD-10, ICD-11 and OMIM but not for SNOMED (due to license agreement). Our cross-reference mapping tool (https://mappings.orphacode.org/) also does not provide information related to SNOMED. It therefore seems to me that the only possibility is to use the mapping file and identify one by one, from the ORPHAcode, the SNOMED identifiers corresponding to the diseases of interest. But maybe you have any advice or tips that could help in this matter?

Thanks in advance for the support. Kind regards,

Annabelle (Orphanet Belgium)

**Comment by caterina-lucano-orphanet** [comment]
Dear Anabelle,
just to clarify the limits of the SNOMED license: at Orphanet we can't release machine-readable alignment mappings ORPHAcodes/SNOMED-CT (as SNOMED releases those only to countries with a license). However, we release annually the human-readable alignment file in Excel format. This file can be manipulated and crossed to other Excel files without breaking any license. 

If I understand correctly what you want to do (having mappings by classification), it is perfectly feasible by using this Excel file.
You can for example extract a specific classification from Arbor, import it in Excel, and then cross it to the mapping Excel file using a VLOOKUP function to obtain the corresponding SNOMED code. Do you think this would be useful?
In any case, it is a provisory situation, as whenever the Belgium license will be active, you will have direct access to the machine-readable files released by SNOMED.

Hope this helps, 
Caterina

**Comment by Orphabe** [comment]
Hi Caterina,

Thanks for the prompt reply.

I think that what the experts would like to receive are "ready-to-use" files which allow them to have direct access to their own needs (in this case, an ORPHAcodes-SNOMED CT mapping Excel file for a specific group of disorders), without going through further manipulation steps. I frequently provide extractions from Arbor for different requests, but it is very difficult for me, given the workload, to do the extra-manipulations in the Excel files myself to respond to all customized requests. 

So now I wonder: how far to go to meet the needs of users of the Orphanet nomenclature? Can it be considered acceptable to provide the mapping files available via Orphadata as well as the associated Arbor file (if necessary), and that experts should then be able to train themselves (or request help from their own support team) on possible manipulations to be carried out in Excel (for example on the VLOOKUP function that you mention)?

I don't know if you have an opinion on this. This is more of a general question that is probably difficult to provide a clear-cut answer to.

Thanks and kind regards,

Annabelle

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 
I am briefly jumping into this, just to clarify your last point... "_How far to go to meet the needs of users to the Orphanet Nomenclature_", this is the difficult part as an helpdesk we try also to provide customized and specific answer/methodology to help users depending on their own knowledge level to the nomenclature and autonomy. 
When necessary and once your provided the most precise answer and files (+short guide about how to process and recover the targeted data) you can consider it is good enough. If necessary usually users came back to us.

Regarding the file yes it is fine to provide the mapping files associated to an Arbor file (with caution that this is dated file, it wont reflect any update made on Nomenclature after you sent it). Also I am usually going with the most specific Group of Disorders level extraction; to not overload them with data they are not looking at (e.g. sending an entire classification).

Hope this helps
Kind Regards
Marie-Cécile
