### ISSUE TITLE
Partial trisomy 7p22.3 

### ISSUE THREAD

**Issue by uunter98** [OD4RD/Main-Help-Desk#243]
Dear Marie-Cecile,

an Austrian expert is missing a code for partial trisomy 7p22.3 1,25Mbp. Is it correct that currently, there would only be a group code for this? Is it an entity that should be created?

Thank you and kind regards
Ursula

**Comment by MCecile-US14** [comment]
Dear @uunter98, 

Thank you for your message. Could you please be more specific ? Which group code are you refering too ? As for any creation request, it is very important to provide us with the maximum of elements.
Could you please also specify detailed elements of the potential missing entity (clinical context, case reports, homogeneous phenotype references, overivew of the Orphanet disease meeting report...).
This will really help to consider and proceed your request further and prioritize it if necessary.

Kind Regards, 
Marie-Cécile

**Comment by uunter98** [comment]
Hi Marie-Cecile,

thank you for your response. I will ask the clinicians, but I doubt they have anything beyond their own case documentation. My understanding is now that these cases will most likely not receive an OrphaCode.

thxx
Ursula

**Comment by MCecile-US14** [comment]
Dear @uunter98, 

Sorry for the delay on this. Honestly I am not sure, as if further others cases are published with the same diagnosis and same loci partial duplication, this might be consider as a creation of a disorder entity (need for coding RD patients).

Please send us the follow up with clinicians if you have some and details about their patient(s).
I will let this issue pending until you let us know. 

Kind Regards, 
Marie-Cécile

**Comment by caterina-lucano-orphanet** [comment]
Hi Ursula, whenever you have news, Riddhi is now following this issue.
Thanks,
Caterina

**Comment by uunter98** [comment]
Dear Caterina,
unfortunately, the clinician is not very compliant, so I think I will close the issue for now and only re-open it in case I get additional info.
Thanks!!!
U

**Comment by uunter98** [comment]
xx
