### ISSUE TITLE
Add OMIM 619988 to ORPHA:88616 Autosomal recessive non-syndromic intellectual disability

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#247]
Dear all,

A Spanish coder suggests to link OMIM [619988 ](https://omim.org/entry/619988)to [ORPHA:88616](https://www.orpha.net/en/disease/detail/88616) Autosomal recessive non-syndromic intellectual disability.

It's a a nonsyndromic neurodevelopmental disorder caused by homozygous mutation in the CEP104 gene ([616690](https://omim.org/entry/616690)) on chromosome 1p36, so the [CEP104](https://www.orpha.net/en/disease/gene/CEP104) gene could also be assigned to this ORPHA.

Kind regards, 

María Elena

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES , 

To check for the linkage between CEP104 and Autosomal recessive non-syndromic intelelctual disability, I need to verified with the following paper PMID: 35359234 could you provide this article or the expert can provide another PMID (the one I give was from OMIM) ?

Best regards, 
Mickael

**Comment by Orphanet-ES** [comment]
Dear @Mickael-Orphanet ,

I have contacted the expert and I hope he can provide me with the document or another reference.
I will let you know when I have any updates.

Best regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Dear @Mickael-Orphanet ,

The expert could not help me obtain the document, but I got it.

[s11033-022-07353-w.pdf](https://github.com/user-attachments/files/17163615/s11033-022-07353-w.pdf)

I hope it will be useful to you.

Kind regards, 

María Elena

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES, 

Thank you so much ! I will review as soon as possible. 

Best regards, 
Mickael

**Comment by Orphanet-ES** [comment]
Dear @Mickael-Orphanet ,

Thanks for your help.
I have informed the expert about it.

Kind regards, 

María Elena
