### ISSUE TITLE
Add OMIM 618533 to ORPHA:90635

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#249]
Dear all,

Please, add the OMIM [618533](https://omim.org/entry/618533) Deafness, autosomal dominant 37 to [ORPHA:90635](https://www.orpha.net/en/disease/detail/90635) Rare autosomal dominant non-syndromic sensorineural deafness type DFNA.

Since it is is caused by heterozygous mutation in the COL11A1 gene ([120280](https://omim.org/entry/120280)) on chromosome 1p21,  [COL11A1](https://www.orpha.net/en/disease/gene/COL11A1) gene could also be linked.

Kind regards, 

María Elena

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES , 
I add OMIM [618533](https://omim.org/entry/618533) to [ORPHA:90635](https://www.orpha.net/en/disease/detail/90635) Rare autosomal dominant non-syndromic sensorineural deafness type DFNA. 

I also linked the gene COL11A1 to [ORPHA:90635](https://www.orpha.net/en/disease/detail/90635) Rare autosomal dominant non-syndromic sensorineural deafness type DFNA. 

Please, beware that the Orphanet website will display those data next week. 

Best regards, 
Mickael

**Comment by Orphanet-ES** [comment]
Thanks @Mickael-Orphanet
