### ISSUE TITLE
How to correctly assign the ORPHA code to the diagnosis: Blepharophimosis-impaired intellectual development syndrome (BIS) associated with SMARCA2 mutations, OMIM #619293?

### ISSUE THREAD

**Issue by AMPilarczyk-PL** [OD4RD/Main-Help-Desk#25]
Searching according OMIM number or name of disease displayed in OMIM generate “No result”, however ORPHA:293642   (Group of disorders)   Blepharophimosis-intellectual disability syndrome does exist with several „children” (Disorders), some  with assigned causing genes.
Searching by gene (SMARCA2) displays 2 answers:
- ORPHA:3051   (Disorder)   Nicolaides-Baraitser syndrome
and
- ORPHA:2728   (Disorder)   Blepharophimosis-intellectual disability syndrome, Ohdo type, however this latter entity is cross-linked with OMIM 249620 with no clear gene assignment

**Comment by MCecile-US14** [comment]
Dear @AMPilarczyk-PL, 
Thank you for reasing this request. After verification and check of the recent literature PMID:32694869 you provided, we created ORPHA:637013 (PatID: 31702) for **SMARCA2-related blepharophimosis-intellectual disability syndrome**. Linked to SMARCA2 gene and classified into the group of disorders ORPHA:293642, Blepharophimosis-intellectual disability syndrome.

This syndrome corresponds to patients presenting SMARCA2 missense variants and a new recognizable phentoype including epicanthal folds, blepharophimosis, and downturned nasal tip along with variable degree of intellectual disability features. Differential diagnosis is made from Blepharophimosis-intellectual disability syndrome, Odho type (ORPHA:2728) and Nicolaides-Baraister syndrome (ORPHA:3051).

Please note we use the opportunity to "clean up" and updated accordingly synonyms and linked/unlinked genes of the group ORPHA:293642 wrongly attributed. This will be visible online by the next day.
Hope this will clarify your search and allow better patient coding, 
Kind Regards, 
Marie-Cécile

**Comment by AMPilarczyk-PL** [comment]
Dear Marie-Cecile
Thank you very much for the creation of the new specialized code for BIS and explanation.
AMPilarczyk-PL
