### ISSUE TITLE
Add OMIM 620725 to ORPHA:610

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#250]
Dear all,

Please, add the OMIM [620725](https://omim.org/entry/620725) Bethlem myopathy 1B to [ORPHA:610](https://www.orpha.net/en/disease/detail/610) Bethlem muscular dystrophy.

The gene COL6A2 associated with this phenotype is already linked to the disease.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES,

Thank you for your request, this will be reviewed in the coming months with your suggestion by the next Orphanet Nomenclature Alignements manager starting in September. We will keep you update once it is done.
Kind Regards,
Marie-Cécile

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES , 
I have added OMIM [620725](https://omim.org/entry/620725) Bethlem myopathy 1B to [ORPHA:610](https://www.orpha.net/en/disease/detail/610) Bethlem muscular dystrophy. 
I have also added the OMIM  [620726](https://omim.org/entry/620726) to [ORPHA:610](https://www.orpha.net/en/disease/detail/610) Bethlem muscular dystrophy.

Please be aware that it takes one week to see the information in the Orphanet website. 

Best regards, 
Mickael

**Comment by Orphanet-ES** [comment]
Thanks @Mickael-Orphanet ,

I have informed the expert about it.

Kind regards, 

María Elena
