### ISSUE TITLE
Add OMIM  617642 to ORPHA:93334 Postaxial polydactyly type A

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#253]
Dear all,

Please, add the OMIM [617642](https://omim.org/entry/617642) Polydactyly, postaxial, type A7 to [ORPHA:93334](https://www.orpha.net/en/disease/detail/93334) Postaxial polydactyly type A.
The gene IQCE associated with this phenotype is already linked to the disease.

Kind regards,

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES,

Thank you for your request, this will be reviewed in the coming months with your suggestion by the next Orphanet Nomenclature Alignements manager starting in September. We will keep you update once it is done.
Kind Regards,
Marie-Cécile

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES , 
OMIM 617642 as been added to ORPHA:93334, it should be visible by next week. 

Best regards, 
Mickael

**Comment by Orphanet-ES** [comment]
Thanks @Mickael-Orphanet
