### ISSUE TITLE
Broken link on the wiki page, point 8

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#254]
Hello,

I just wanted to let you know that a link is broken in the text related to the point 8 of the wiki pages dedicated to Orphanet‐ERN collaborations.

"For more information related to ERNs: click [here](https://www.orpha.net/consor/cgi-bin/Clinics_ERN.php?lng=EN)"
--> Link to be replaced with: https://www.orpha.net/en/expert_centres/european-reference-network

Kind regards,

Annabelle (Orphanet Belgium)

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 

Thank you for pointing this out! It is fixed :)
Kind Regards, 
Marie-Cécile
