### ISSUE TITLE
Add OMIM 620150 to ORPHA:312 Autosomal dominant epidermolytic ichthyosis

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#255]
Dear all,

Please, add OMIM [620150](https://omim.org/entry/620150) Epidermolytic hyperkeratosis 2A, autosomal dominant to [ORPHA:312](https://www.orpha.net/en/disease/detail/312) Autosomal dominant epidermolytic ichthyosis.

The KRT10 gene related to this OMIM is already linked to ORPHA.

Kind regards, 

María Elena

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES ,
I have added OMIM OMIM [620150](https://omim.org/entry/620150) Epidermolytic hyperkeratosis 2A, autosomal dominant to [ORPHA:312](https://www.orpha.net/en/disease/detail/312) Autosomal dominant epidermolytic ichthyosis 
I have also unlink OMIM [607602](https://omim.org/entry/607602)  that was wrongly aligned to this entity. 

Best regards, 
Mickael

**Comment by Orphanet-ES** [comment]
Dear @Mickael-Orphanet ,

Thanks for your help.

Kind regards, 

María Elena
