### ISSUE TITLE
How to correctly assign ORPHA code to Charcot-Marie-Tooth disease, considering extremely wide genetic background?

### ISSUE THREAD

**Issue by AMPilarczyk-PL** [OD4RD/Main-Help-Desk#26]
Results displayed include 95 entities, some with the causative gene included to in the disease name or to its synonyms, e.g. **ORPHA:487814**   (Disorder)   Autosomal dominant Charcot-Marie-Tooth disease type 2 due to DGAT2 mutation

**Comment by MCecile-US14** [comment]
Dear @AMPilarczyk-PL ,

Sorry for the late reply. For this type of genetic disease such as CMT with a wide genetic background we do recommend to always start the search by using gene name or symbol to first filter these gene associated-entities and then assign the correct clinical diagnosis resuming the patient phenotype associated to this gene or ORPHAcode.

I also invit you to use and share this short video tutorial explaining [a gene search using Orphanet](https://www.youtube.com/watch?v=yNlizny6t0k)
Kind Regards, 
Marie-Cécile
