### ISSUE TITLE
Confirmation of mapping  to ICD-10 Q87.4 for ORPHA:60030 Loeys-Dietz syndrome

### ISSUE THREAD

**Issue by OrphanetSweden** [OD4RD/Main-Help-Desk#260]
Dear all,

We were hoping you could confirm that the mapping to ICD-10 is correct for ORPHA:60030 Loeys-Dietz syndrome. The mapping listed in Orphanet resources is to ICD-10 Q87.4 (Marfan syndrome) NTBT. The Swedish board of Helath and wellfare are using ICD-10 SE "Q87.8W Other specified congenital malformation syndromes, not elsewhere classified" for the disorder, which should correspond to "Q87.8 Other specified congenital malformation syndromes, not elsewhere classified" in the international classification. 

The question arose while handeling a coding request from the Information centre for rare diseases. 

Best regards,
Orphanet Sweden

**Comment by MCecile-US14** [comment]
Dear @Seed-Orphanet,

Could you please check this request for ICD-10 alignment and let @OrphanetSweden know the final decision ?
(General reminder: the database is currently not accessible for any modifications, please note we cannot guarantee when the changes can be implemented)
Thank you,
Marie-Cécile

**Comment by Seed-Orphanet** [comment]
Dear Orphanet Sweden team,

Thank you for your message. I can confirm that the current alignment of ORPHA:60030 Loeys-Dietz syndrome to ICD-10 Q87.4 (Marfan syndrome) is correct. While this alignment is not specific (given the NTBT attributed relationship of the code), it reflects the clinical similarities between Loeys-Dietz syndrome and Marfan syndrome. Given that Loeys-Dietz is a Marfan-related syndrome, this is the closest match available within the ICD-10 classification.
I hope this clarifies our approach.

Kind regards,
Seed
