### ISSUE TITLE
New code for phenytype related to ANO5 mutation?

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#266]
Dear Orphanet,
One of our medical doctors working at the expert centre for rare neuromuscular disorders has patients with mutation in ANO5 but with a phenotype that does not match any of the disorders in Orphanet. In her opinion, it would be best if a new diagnosis with it's own code was created.

Description of the phenotype by the MD is "Phenotype with high CK, sometimes a history of rabdomyolysis and sometimes pain". She has sent us two scientific papers (attached).
[de Bruyn_et_al_2023_ANO5-Clinicial-Genetic-findings.pdf](https://github.com/user-attachments/files/17040370/de.Bruyn_et_al_2023_ANO5-Clinicial-Genetic-findings.pdf)
[Avarese_et_al_2015_ANO5_phenotypes.pdf](https://github.com/user-attachments/files/17040371/Avarese_et_al_2015_ANO5_phenotypes.pdf)

Some more input from the professional:
"I think they should have their own code, otherwise it will be difficult to find it when searching in Orpha. It is very possible that during a lifetime you can go from one phenotype to the other, i.e. gradually develop atrophy/paresis - I have seen it in the clinic. The phenotype has only sky-high CK and possibly some myalgias. One patient is less likely to "convert" to one of the other phenotypes."

The expert centre: https://www.orpha.net/en/expert-centres/centre/616691?name=eman&consulting=medical&age=all&official=0

Kind regards,
Lene

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @LeneMartinsen,

I am coming back to you to ask you for some details regarding this request. In de documentation, I realised that mutations in the ANO5 gene can lead to distinct muscular disorders: 

- limb–girdle muscular dystrophy type R12 (LGMDR12)
- Miyoshi distal myopathy type 3 (MMD3)
- metabolic myopathy-like (pseudometabolic) phenotype
- asymptomatic hyperCKemia

LGMDR12, MMD3, and asymptomatic hyperCKemia are already in Orphanet, and thanks to this revision, we will add the link to ANO5 to asymptomatic hyperCKemia (in Orphanet: ‘Isolated asymptomatic elevation of creatinine phosphokinase, ORPHA:206599).

I was wondering if the requested ORPHA code might fit the so-called 'metabolic myopathy-like (pseudometabolic) phenotype' also known as 'ANO5 muscular dystrophy' or 'anoctaminopathy-5' (PMID: 24889862, 23663589). 
According to the literature (PMID: 36292621), myalgia, exercise intolerance and/or rhabdomyolysis without muscle weakness are the main clinical features of patients in this group. These symptoms mimic the classic manifestations of metabolic myopathies, hence the term pseudometabolic phenotype.
A proportion of these patients subsequently convert to the LGMDR12 or MMD3 phenotype. With a median follow-up period of 5 years, the vast majority of patients with myalgia remained stable without clinical weakness. CK levels range from 200 to over 47,000 U/L, and some patients may have hyperCKemia long before they become symptomatic. Rhabdomyolysis can also occur in anoctaminopathy-5 patients with overt weakness. Some patients present with cardiac involvement with septal hypokinesis and supraventricular tachycardia. Amyloid deposition in muscle also a key feature and can be helpful in the diagnosis.

Could you please confirm with the MD whether this entity reflects the aforementioned patients and sufficiently meets the coding needs?

Thank you very much in advance for your help,
Best

Marta

**Comment by LeneMartinsen** [comment]
Dear Marta,
Thank you very much. I have sent the question to the MD and will get back to you as soon as she replies.

Best,
Lene

**Comment by LeneMartinsen** [comment]
Dear Marta,
The MD confirmed that the phenotype you describe reflects the patients and will meet the coding needs.

Best,
Lene

**Comment by Orphanet-MartaFructuoso** [comment]
Dear Lene,
 
Thank you very much for your prompt reply. The creation of this ORPHAcode will then be presented at our next medical and scientific meeting. I will get back to you soon with the decision.

Best regards,
Marta

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @LeneMartinsen,

Based on the current literature, Orphanet's medical and scientific committee has validated the creation of ORPHA: 689021 for this ANO5 gene-related muscular disorder. In line with the main clinical features, the main name of ORPHA: 689021 is 'Asymptomatic hyperCKemia-myalgia-rhabdomyolysis syndrome'. According to the Orphanet workflow, more information on this entity will soon be available on the website.

Kind regards,
Marta
