### ISSUE TITLE
New code for Shashi-Pena syndrome

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#267]
Dear all,

A Spanish coder requests the creation of an ORPHAcode for the **Shashi-Pena syndrome**, a neurodevelopmental syndrome characterized by delayed psychomotor development, variable intellectual disability, hypotonia, facial dysmorphism, and some unusual features, including enlarged head circumference, glabellar nevus flammeus, and deep palmar creases. Some patients may also have atrial septal defect, episodic hypoglycemia, changes in bone mineral density, and/or seizures.

References: 
OMIM  [617190](https://omim.org/entry/617190)
NORD https://rarediseases.org/rare-diseases/shashi-pena-syndrome/
MedGen https://www.ncbi.nlm.nih.gov/medgen/934639

Kind regards, 

María Elena

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES, 
Based on current literature (PMID:27693232, 37493007), Orphanet medical and scientific committee has validated the creation of ‘Shashi-Pena syndrome’, ORPHA:689408. A rare malformation syndrome characterized by developmental delay, hypotonia and a distinct facial dysmorphism. Facial dysmorphism is characterized by glabellar nevus flammeus, hypertelorism, arched eye-brows, prominent eyes, a broad nasal tip and minor ear abnormalities. Hypoglycemia is common amongst patients. Atrial septal defect during the newborn patients is also present. Brain abnormalities, and skeletal manifestations have been observed in some patients. Patients present macrocephaly, normal height and weight and more variability in the degree of cognitive impairments. The prevalence is unknown but the rarity has been established. 

Thank you for your demand. 

Best regards, 
Mickael

**Comment by Orphanet-ES** [comment]
Dear @Mickael-Orphanet ,

Thanks for your help.

I will inform the expert as soon as the name in Spanish is displayed, which I just translated.
As for the relationship with OMIM, why is it not shown on Orphanet? Has it not been linked yet or is it a technical problem?

Kind regards,

María Elena

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES , 

I have done it yesterday, so it will be visible by next week. 

Best, 
Mickael
