### ISSUE TITLE
Comparison of SNOMED CT-ORPHA codes: examples requiring explanation

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#268]
Dear colleagues,

A clinician and coder presented us with various examples which could suggest that SNOMED CT is a more “detailed” terminology than Orphanet for certain rare diseases, which of course is not in line with the message we want to convey.

Here are some of these examples:

• In Orphanet, there are no distinct entities within von Willebrand disease type 1 (ORPHA:903), whereas types 1A, 1B and 1C exist in SNOMED CT. And according to the expert, they do have clinical utility.

• In Orphanet, there are no subtypes of Autosomal dominant polycystic kidney disease (ORPHA: 730), whereas in SNOMED CT, we distinguish between the pediatric form and the adult form (with 2 types).

• In Orphanet, cystic fibrosis is represented by only 2 ORPHAcodes (ORPHA:586 “Cystic fibrosis” and ORPHA:2575 “Cystic fibrosis-gastritis-megaloblastic anemia syndrome”), whereas in SNOMED CT, there is a whole series of codes depending on the type of causal mutation, the affected organ, etc.

In these 3 examples, could you explain why Orphanet did not consider it relevant to create the ORPHAcodes corresponding to the SNOMED IDs? I'm sure there are good reasons for this, based on our own inclusion rules, and it's not just errors or missing entities. But I don't know which ones, and I would really like to counter this widespread idea in my country according to which the SNOMED CT terminology is in reality "better" than the Orphanet nomenclature even when it comes to rare diseases.

Thank you very much for your support, kind regards,

Annabelle (Orphanet Belgium)

**Comment by Seed-Orphanet** [comment]
Dear Annabelle,

Thank you for bringing this to our attention. It is important to address these concerns, and I'd be happy to provide some context on why Orphanet has structured certain rare disease codes differently.

While SNOMED CT may offer more granular coding for certain disorders, Orphanet is the primary source of rare disease data, which will then be reproduced by SNOMED CT, as part of an ongoing collaboration. Moreover, SNOMED CT does not fully cover all of the rare diseases present in the Orphanet database and does not specifically categorize these diseases as "rare." Therefore, relying solely on SNOMED CT for coding rare diseases limits the ability to retrieve precise data and to make statistical analysis on rare diseases.

Now, regarding the specific examples you raised:

1. Von Willebrand disease: while it is true that Orphanet does not have a code for the type 1C, we do include types 2A, 2B, 2M, 2N, and type 1 at the subtype level. However, I have not found any mention of types 1A or 1B in the literature. Subtypes are created when there are specific clinical signs, disease management, or treatment approaches that differentiate patients into distinct groups within the diagnosis. In the case of von Willebrand disease type 1C, which is the one we are missing, it may be that there are no sufficiently distinct clinical features to justify a separate subtype. We will review this issue and consider creating a new subtype if it is deemed clinically relevant.

2. Autosomal dominant polycystic kidney disease (ORPHA:730): if the perimeter of the disorder is the same in pediatric and adult patients, we create only one ORPHAcode.  In this case, both children and adults with this condition seem to share the same clinical signs, so we cover them under ORPHA:730. We do, however, mention the age of onset in the ID card of the disease, which specifies both onset in childhood and adulthood.

3. Cystic fibrosis: ORPHAcodes describe a diagnosis, and not phenotypic variations. If the diagnosis of a disease remains the same regardless of the mutation or organ involved, we use a single ORPHAcode for the condition.

Thank you again for raising these important points.  I understand the frustration this situation may cause, and I hope this response clarifies our approach and  helps to justify why ORPHAcodes are so important for accurately coding rare diseases.

Kind regards,
Seed
