### ISSUE TITLE
Error 500 in Orphanet website for all new created and inactivated entities

### ISSUE THREAD

**Issue by Mickael-Orphanet** [OD4RD/Main-Help-Desk#269]
Dear @uunter98 , 

I create this issue because for now, newly created and inactivated entities are showing errors because they are not classified. We're actively working on a fix and will keep you updated once the issue is resolved.

Best regards, 
Mickael 
![372623077-98ae0214-5a44-470a-b70c-d41232163250](https://github.com/user-attachments/assets/02594096-4315-493d-bc77-2ddd9cd9d3c6)

**Comment by uunter98** [comment]
Thank you, @Mickael-Orphanet !!
