### ISSUE TITLE
CTNND2-related neurodevelopmental disorder

### ISSUE THREAD

**Issue by uunter98** [OD4RD/Main-Help-Desk#273]
Dear Mickael,
a coder from Austria has a pediatric patient with a neurodevelopmental clinical picture and a CTNND2 mutation. It is documented that CTNND2 is related to autism spectrum disorder, but I am not sure if it is distinct enough to create a new entity. Here is what I found: https://medlineplus.gov/genetics/gene/ctnnd2/#conditions, PMIDs 33718894 and 25807484; OMIM lists nothing. For now, there is no code for this patient. I would be very grateful for your advice.
Thank you and kind regards
Ursula

**Comment by Mickael-Orphanet** [comment]
Dear @uunter98 , 

Based on the current scientific  literature, Orphanet medical and scientific committee have detected that there is no specific clinical  and following our procedure on intellectual disabilities entries we will link CTNND2 to Autosomal dominant non-syndromic intellectual disability  ORPHA:178469.

Best regards, 
Mickael
