### ISSUE TITLE
ORPHA:268920 (Isolated megalencephaly) classification

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#274]
Hello,

In the Rare genetic disease classification, ORPHA:268920 (Isolated megalencephaly) appears directly under the group of disorders ORPHA:269553 (Genetic cerebral malformation). Is this correct?

Thanks

**Comment by OrphanetSwitzerland** [comment]
Related to this issue, the entity ORPHA:268920 (Isolated megalencephaly) is currently the only subtype under ORPHA:2477 - Megalencephaly.

**Comment by Riddhi-Orphanet** [comment]
Dear @OrphanetSwitzerland ,
Yes exactly, I completely agree with you regarding this query:
  
 Genetic cerebral malformation **( ORPHA:269553) is a Group of disorders** and Isolated megalencephaly **(ORPHA:268920) is the subtype of this group of disorder**. However as you know that we have multiparental system, it is also classified under different group of disorders and  the **preferential parent for it is Rare developmental defect during embryonesis (ORPHA:93890)** and under this group of disorder, there is the **DISORDER Megalencephaly**  (ORPHA:2477) and under which as you have pointed out the entity ORPHA:268920 (Isolated megalencephaly) is currently the only subtype. 

Hope this helps!

Best,
Riddhi Jani

**Comment by OrphanetSwitzerland** [comment]
Dear Riddhi,

Thank you for the feedback.

We weren’t sure if it’s standard to have a subtype directly under a group of disorders, but based on what you said, we understand that it’s acceptable.

Regarding the other comment, we were informed in a RIC ticket (http://redminor.orpha.net/issues/18013), that “for a disorder to have only one subtype is indeed an inconsistency as it goes against the Orphanet classification standards. Generally speaking, a disorder should have at least 2 or more subtypes, and the subtype level must cover the complete perimeter of the disorder”.

Kind regards

**Comment by Riddhi-Orphanet** [comment]
Dear @OrphanetSwitzerland,

Yes you are right, we are actually revising it  currently but it will take a while till it gest accepted in our final disease meeting. So till then you will still have this one subtype appearing on orphanet. I will upate you as soon as the changes have been finalized and updated on orphanet.

Best,
Riddhi
