### ISSUE TITLE
Mapping lists ICD-10 per ERN 

### ISSUE THREAD

**Issue by uunter98** [OD4RD/Main-Help-Desk#277]
Hi Riddhi,
I have heard from an Austrian MoH representative (who has heard it in the last BoMS meeting) that there are now mapping lists ICD-10/Orpha available per ERN field. Is that correct, and if so, could make those lists available to me/us (ursula.unterberger@meduniwien.ac.at)? I would also be interested in the specifications of those lists, e.g. when were they extracted, how were they prepared.
Thank you and kind regards
Ursula

**Comment by Riddhi-Orphanet** [comment]
Dear Ursula,
We are currently doing gap anaplysis and we have sent a compiled file to the ERNs but havent received anything from them yet.

Best,
Riddhi

**Comment by Riddhi-Orphanet** [comment]
Dear Ursula,

I am closing this issue for now as this is ERN dependent and as soon as we have the answer from them we will let you know
