### ISSUE TITLE
1q22q23.1 Microdeletion

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#279]
Hello,

The Service of Genetic Medecine at CHUV (Lausanne hospital) has a patient with a heterozygous interstitial microdeletion with a minimum size of 1.1 Mb on the long arm of chromosome 1 at 1q22q23.1. 

We found one paper describing a single patient with a similar condition: “A de novo 1q22q23.1 Interstitial Microdeletion in a Girl with Intellectual Disability and Multiple Congenital Anomalies Including Congenital Heart Defect”: PMID: 29421787

Is it possible to include this entity in the nomenclature despite only one patient having been described?

Thanks

**Comment by Riddhi-Orphanet** [comment]
Dear @OrphanetSwitzerland,
Thanks for your question. As in Orphanet, we cannot create unless there are atleast two publications, we cannot create this one.
However, if you could encourage them to publish a paper with this new patient, we will create it then.
Hope this helps!

Best,
Riddhi
