### ISSUE TITLE
ORPHA:5: wrong mapping with SNOMED?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#286]
Dear all,

In the 2024 version of the ORPHAcodes-SNOMED IDs mapping file, we notice that ORPHA:5 "Long chain 3-hydroxyacyl-CoA dehydrogenase deficiency" is aligned on 2 SNOMED IDs:

- 726021008, "Long chain 3-hydroxyacyl-CoA dehydrogenase deficiency", see: https://bioportal.bioontology.org/ontologies/SNOMEDCT?p=classes&conceptid=726021008

- 1230273004, "Megaconial congenital muscular dystrophy", see: https://bioportal.bioontology.org/ontologies/SNOMEDCT?p=classes&conceptid=1230273004

The mapping ORPHA:5- SNOMED 1230273004 is surprising to us because at first sight, it doesn't seem to represent the exact same clinical entity and moreover, because another ORPHAcode is mapped with the same SNOMED ID in the file: ORPHA: 
280671 "Megaconial congenital muscular dystrophy".

Could you please have a look at this alignments? 

Thanks in advance for the support, kind regards,

Annabelle (Orphanet Belgium)

**Comment by Seed-Orphanet** [comment]
Dear @Orphabe 
now that the mapping file has been corrected and reuploaded on ORPHAdata, the ORPHA:5 maps correctly to SNOMED CT ID 726021008, "Long chain 3-hydroxyacyl-CoA dehydrogenase deficiency". Thank you for signaling this to us!

Kind regards,
Seed
