### ISSUE TITLE
Synonyms for a deprecated disease

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#290]
Dear all, 

Regarding deprecated diseases, I wonder what the policy is regarding names and synonyms, and whether they are assigned to the replacement code.

For instance, ORPHA:374 [Goldenhar syndrome](https://www.orpha.net/en/disease/detail/374) have moved to [Oculo-auriculo-vertebral spectrum](https://www.orpha.net/en/disease/detail/141132), and that name has been added as a synonym, but not the other names of the disease.

But in other cases, neither the name nor the synonyms have been assigned to the active code.

Is there any rule about it?

Kind regards, 

María Elena

**Comment by Orphanet-AysegulSenol** [comment]
Dear Maria Elena, 

I just wanted to update you that "Goldenhar syndome" is removed from the synonymes of Oculo-auriculo-vertebral spectrum as it was indeed not correct to keep this synonyme. By definition "deprecated" entity is considered as the part of the "targetted" entity that is larger in perimeter, thus can not be an exact synonyme. In certain cases it/they may be kept as a keyword(s) but this should be evaluated case by case, there is not a certain rule for that. 

Thank you for noticing and bringing it up this issue and please let us know if you come across similar issues.

Best wishes, 

Aysegul

**Comment by Orphanet-ES** [comment]
Dear @Orphanet-AysegulSenol ,

Thanks for the clarification
I have already deleted the Spanish synonym so there is no confusion on the matter.

Kind regards, 

María Elena
