### ISSUE TITLE
Will we still need Orphacodes when ICD-11 has been implemented?

### ISSUE THREAD

**Issue by uunter98** [OD4RD/Main-Help-Desk#30]

**Comment by JTorphanet** [comment]
Hello @uunter98 ,

Orphanet has an ongoing outstanding collaboration with the WHO to produce a better representation of  rare diseases in ICD-11. At the moment, a good proportion of the Orphanet clinical entities is included in ICD-11 (we have for the moment completed the alignment of 32% of Orphanet clinical entities with ICD-11, 20% with an exact code-to-code relationship). However, most rare diseases are present in the Foundation and not in the MMS. These diseases are represented by a URI and not a code which in the majority of cases cannot not be used in medical/public health practice. Moreover, this system does not allow to identify a disease as rare.    More precise information about this topic will also be available when the alignment process between the two terminologies will be completed. A document clarifying more aspects about the alignment between ORPHAcodes and ICD-11 will be produced in the next future.

Best, 

Julie
