### ISSUE TITLE
How can I encode a disease that doesn’t have a genetic base?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#34]
This is a question received with regard to a registration in the Belgian Central Registry for Rare Diseases (CRRD). Registration in the CRRD is actually not limited to patients with a genetic diagnosis but can also be based on clinical characteristics, family history or a combination of these. Confusion may arise from the fact that we currently only receive records from genetic centres, but it does not have to be with molecular diagnosis.

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 

Sorry for this late reply and thank you for pulling up this common question, you can find official Orphanet answer in the Wiki page of this Github [Wiki/ORPHAcodes#are-non-genetic-diseases-classified-by-orphacodes](https://github.com/OD4RD/Main-Help-Desk/wiki/ORPHAcodes#are-non-genetic-diseases-classified-by-orphacodes).

Kind Regards, 
Marie-Cécile
