### ISSUE TITLE
Hyperlinks ORPHAcodes

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#35]
Question from a coder: 

"I am coming back to you to find out if the Orphanetbelgium team could possibly help us integrate the hyperlinks of all the ORPHAcodes into our EPIC system.

Indeed, via our rare disease alert, and via the ORPHAcode that we have on our "rare disease" form, we would like to go directly to the page of the corresponding disease and not to the general Orphanet site (which is currently the case).

Our EPIC team explained to us that it is difficult to make the automatic link because the code on the hyperlink is not the same as the ORPHAcode and the only way to achieve this is to add one by one for each ORPHAcode which will require a huge amount of work..

Do you have a list of these ORPHAcode hyperlinks, which we could offer to our EPIC team? We would also like, as far as possible, to benefit from your expertise in this area to see if there is another solution".

**Comment by Orphanet** [comment]
For historical reasons and retro-compatibility with previous version of the Orphanet's website (back in 2000) we have kept a specific format to perform backlinks to the website (based on Orphacodes):

https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng={Lng}&Expert={id}
where {lng} is the two letter ISO code for a language and {id} still the Orphacode digit

ex:
Marfan syndrome
ORPHA:558
=>
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=En&Expert=558

Then, based on Orphacode, you should be able to build link to the dedicated page on Orphanet.

(From API, it's even more simple, as we have a dedicated "GET" to obtain url):
https://api.orphacode.org/#/Orphanet%20URL/list_url
/{lang}/ClinicalEntity/orphacode/{orphacode}/OrphanetURL (Two parameters: Orphacodes and ISO for language.)
ex :
curl -X GET "https://api.orphacode.org/EN/ClinicalEntity/orphacode/558/OrphanetURL"
=>
{
  "OrphanetURL": "http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=558",
  "ORPHAcode": 558,
  "Date": "2022-06-14 08:03:22"
}

Best regards,

**Comment by Orphabe** [comment]
Thank you very much for your answer, Marc. 

Regarding the API: in the event that there is a problem accessing the internet from the hospital (in some hospitals access is blocked for security reasons), is it correct that you are working on a solution in which you can provide a database that can be installed locally. If so, do you have an estimate of when this local facility will be available?

Thank you, kind regards,

Annabelle (on behalf of the Belgian team)
