### ISSUE TITLE
OMIM 615349 - Ehlers-Danlos syndrome subtypes

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#40]
Dear all, 

We have been informed about a discrepancy between Orphanet and OMIM.

According to OMIM database (https://omim.org/entry/615349), it is related only to "Ehlers-Danlos syndrome, spondylodysplastic type, 2", that correspond to ORPHA:536467.

But regarding OMIM 615349, on Orphanet database it is related to two entities:
ORPHA:536467  B3GALT6-related spondylodysplastic Ehlers-Danlos syndrome (type 2)
ORPHA:75496  B4GALT7-related spondylodysplastic Ehlers-Danlos syndrome (type 1)

And on dataviz, the relation EDS typ2 and OMIM 615349 is exact, but the relation EDS type 1 and OMIM 615349 is BTNT.
As this can be somewhat confusing for users, if it is correct, could you provide me with a document that supports it so that I can inform the expert?

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Hi María Elena, 

As you highlighted, there is a misalignment. I will proceeed to the following changes for the ORPHAcode 75496: 
- remove the OMIM number #615349
- Correct the relationship as exact for the OMIM number #130070
So, I confirm that EDS type 1 (OPRHA 75496) is linked to OMIM #130070 as exact and EDS type 2 (ORPHA 536467) is linked to OMIM #615349 as exact. 

These changes will be visible on the website in the next 48h. 

Julie

**Comment by Orphanet-ES** [comment]
Thanks Julie!

María Elena
