### ISSUE TITLE
OMIM 617101 - ORPHA:619233

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#41]
Dear all, 

According to a Spanish expert, the OMIM 617101 is related to ORPHA:619233.

https://omim.org/entry/617101
INTELLECTUAL DEVELOPMENTAL DISORDER WITH PERSISTENCE OF FETAL HEMOGLOBIN
Alternative titles; symbols
DIAS-LOGAN SYNDROME
INTELLECTUAL DEVELOPMENTAL DISORDER WITH HEREDITARY PERSISTENCE OF FETAL HEMOGLOBIN

ORPHA:619233  Hereditary persistence of fetal hemoglobin-intellectual disability syndrome
Synonym(s) : Dias-Logan syndrome

Please tell me if you agree so that I can inform the expert of the change.

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Hi María Elena, 
I confirm this alignment (OMIM #617101 link to ORPHAcode 619233), visible in the next 48h on our website. 
Thanks for your collaboration, 
Julie

**Comment by Orphanet-ES** [comment]
Thanks Julie!

María Elena
