### ISSUE TITLE
Perineural cyst: ICD-10 and ICD-11

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#45]
Dear Julie,

Regarding **ORPHA:65250** Perineural cyst (Tarlov syndrome). the ICD-10 currently assigned by Orphanet is **G54.8** (Other nerve root and plexus disorders).

But a Spanish patient organization has told us that there is a new ICD-10 for ORPHA:65250, **G96.191**.
This code corresponds to the clinical modification of the Spanish version of the ICD-10:
https://eciemaps.mscbs.gob.es/ecieMaps/browser/index_10_mc.html 
G96.191 Quiste perineural 2022
Quiste de raíz de nervio cervical
Quiste de raíz de nervio lumbar
Quiste de raíz de nervio sacro
Quiste de raíz de nervio torácico
Quiste de Tarlov

Although the international ICD-10 is not that specific, I understand that it makes sense to assign to ORPHA:65250 the higher level **G96.1** (Disorders of meninges, not elsewhere classified) instead of the ICD-10 code currently assigned:
https://icd.who.int/browse10/2019/en#/G96.1

On the other hand, searching by "Tarlov cyst" on the ICD-11, I have arrived at the code **8D6Y** (Other specified disorders of cerebrospinal fluid pressure or flow).
https://icd.who.int/browse11/l-m/en#/http://id.who.int/icd/entity/23958598/mms/other

And on the ICD-11 Coding Tool:
8D6Y
Other specified disorders of cerebrospinal fluid pressure or flow
Matching Terms
Tarlov cyst
Related categories in maternal chapter
Diseases of the nervous system complicating pregnancy, childbirth or the puerperium / Other specified disorders of cerebrospinal fluid pressure or flow(JB64.3/8D6Y)

I am not an expert in the use of the ICD but I understand that the two codes that I propose are adequate for ORPHA:65250:
ICD-10: **G96.1**
ICD-11: **8D6Y**

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES , 

I have reviewed your suggestion about ORPHA 65250. 

First of all, Orphanet is an international classification and by definition, aligned only with other international medical classifications. In that sense, we do not verify the “national” ICD10-CM database and the newly codes associated. 

In ICD10, G96.1 “Disorders of meninges, not elsewhere classified” is too restrictive and not properly good to describe the clinical entity “perineural cysts”. We confirm the code G54.8. 

Concerning ICD11, we need to align for the moment with two codes: 8D6Y for Other specified disorders of cerebrospinal fluid pressure or flow (found with the keyword Tarlov cyst) and 8B9Y Other specified nerve root or plexus disorders (found with the keyword Perineural cyst, and in line with ICD10 code). In the meantime, we will transfer this example to the WHO ICD11 team to review these codes and remove ambiguity. 

Moreover, I would like to draw your attention to the fact that this entity is probably non-rare. I have requested an epidemiological study and according to the analysis, we will do the appropriate action. 

Best, 

Julie

**Comment by Orphanet-ES** [comment]
Dear Julie, 

Thanks for your comment.

I knew that national modifications are not taken into account when assigning the ICD10 in Orphanet, but I thought that the "higher" level of the specific national code might be relevant.
If you consider that the ICD10 code  G96.1 is too restrictive, it's no problem for me, you are the expert.

As you think that this entity is probably non-rare, I will wait for your analysis to inform the Spanish PO about your final decision.

Best, 

María Elena
