### ISSUE TITLE
Searching for ORPHAcode in Dataviz

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#48]
Dear all, 

As you know, Dataviz has the option to search by ORPHAcode, preferred term, synonym, ICD-10, ICD-11 or OMIM code.
But, when searching for a number, if that number exists as an OMIM code and as an ORPHA code, it only returns the result of the OMIM code.

For example, OMIM 300605, which would correspond to Retinitis pigmentosa, and ORPHA:300605, which corresponds to Juvenile amyotrophic lateral sclerosis.

In these cases, to obtain the result of the ORPHA code, it must be specifically selected when performing the search ("Select the type of query: ORPHAcode").

But shouldn't it always show both results?

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear Maria Elena, 

Thank you for bringing up this issue. You are right, when you search with the "type of query" set up with "auto", it shows by default OMIM result. It should indeed show both results or at least to discriminate it towards the ORPHAcode so I asked the technical IT team to fix the issue asap and also to find a way to display the list of OMIM references in that case in a more concise way (here all in one long column). I will elt you know when it is fixed.

Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear Maria Elena, 
To follow up on your request, IT team informed us that this Dataviz issue will be solved during the next update of the Dataviz tool, coming with the generation of the new Nomenclature Pack (release July 2023). After then, you should be able to see the change.
I will leave this issue open until it is really solved. Feel free to share other suggestions with us about this as we could maybe implement or update some options available on Dataviz.

Kind Regards, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 , 

Thanks for the update.

While the problem is solved, it seems like a very good idea to add that disclaimer note so that our users are not surprised if, when searching for an ORPHAcode, they do not get the expected result.

Good luck fixing the problem.

Kind regards, 

María Elena
