### ISSUE TITLE
Spinocerebellar ataxia type 3 - age of onset

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#51]
Dear all, 

Regarding ORPHA:98757 Spinocerebellar ataxia type 3 (PatId 13774), there is a discrepancy between the age of onset of the disease and its subtypes. 
Could you confirm this information?

ORPHA:98757 Spinocerebellar ataxia type 3 (PatId 13774)
Age of onset: **Childhood, Adolescent,** Adult

ORPHA:276238 Machado-Joseph disease type 1 (PatId 20359)
Age of onset: Adult

ORPHA:276241 Machado-Joseph disease type 2 (PatId 20360)
Age of onset: Adult

ORPHA:276244 Machado-Joseph disease type 3 (PatId 20361)
Age of onset: Adult

In the description of the disease it seems that it occurs only in adults, although I have found an article of a case of onset in childhood.
https://pubmed.ncbi.nlm.nih.gov/31565539/

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear Maria Elena, 

Thank you for the notice. I will assigned this request to our epidemiologist manager so she can confirm the age of onset, while she will join GitHub channel here. We will come back to you as soon as possible.
Kind Regards, 
Marie-Cécile

**Comment by moi-epiUS14** [comment]
Thank you for your comment, I took a look into your inquiry. 
Indeed, childhood onset can be verified in type 1, but adolescence onset was not recognized. 
Thus, I added childhood onset for type 1 and removed adolescence onset.
