### ISSUE TITLE
ORPHA:616874 + group of disorders

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#52]
Dear all,

As I understand it, according "Why ORPHAcoding" presentation, the orpha ORPHA:616874 (Rare disorder without a determined diagnosis after full investigation) should be used in conjunction with a disorder group ORPHAcode to guide future diagnosis.

But, if the disease has a multisystemic presentation, how to determine which ORPHA group codes to assign?
For example, the patient presents diabetes, retinopathy, deafness, renal disease, cardiomiopathy...
Could all the ORPHAs of these disease groups be assigned?

Because this is not the case of a confirmed diagnosis in which we only assign an ORPHAcode.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear Maria Elena,  

Thank you for your request, I will add a specific post about ORPHA:616874 in the Wiki page in the coming days.

- First, could you please specify what "why ORPHAcoding" presentation you are refering to?

- From what I understand, I think there might be a confusion with terms here. 
In our recommendation slide provided in each training it is specified "Use the new code (ORPHA:616874 : Rare disorder without a determined diagnosis after full investigation), **alone or in addition to the diagnostic assertion**. Provide a phenotype and a genotype description of undiagnosed patients, moreover in registries." 
In our guidelines you can find here [RD-CODE guidelines for coding undiagnosed patients](http://www.rd-code.eu/wp-content/uploads/2022/02/D5.2_RDCODE_VF2021_FV.pdf), you can read details about ORPHA:616874 such as "A rare disorder for which all reasonable efforts have been done by rare diseases experts to determine a diagnosis according to the state of the art and available diagnostic capabilities, but **did not enable to conclude on a clinically known concept**. It is recommended to restrict the use of this entity for coding purpose to rare disease experts."

I would like to draw your attention that we recommend to specify or add extra comment in a free field of text or comment to keep informations or guide other investigation/patient registries as a **phenotypic description, not an ORPHAcode assertion**.

Most of the syndromes are multisystemic, In your case no group of disorders ORPHAcode should be used in addition with ORPHA:616874, it has to be used in specific cases and always stands alone as ORPHAcoding. 

Please let me know if it is still unclear,
Kind regards, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear Marie-Cécile,

Regarding "why ORPHAcoding" presentation, I meant the one included in the Trainers-Toolkit:
https://network.orphanet.org/ejprd_t14-1_trainers-toolkit/ 
[Why ORPHAcoding slidedeck](https://www.canva.com/design/DAEsCf6N5oM/R_fLY-P6RH5PQxVi7tXmkA/view?utm_content=DAEsCf6N5oM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)
On the slide 29, the text in notes is:
_In the frame of the RD-CODE project, the best solution was to rely on the Orphanet classification that is currently implemented in the participating countries. Use of the Orphanet classification group levels (the higher up the lower the level of diagnosis definition)._

Maybe this presentation is previous to the RD-CODE recommentations...

In any case, regarding the document [RD-CODE guidelines for coding undiagnosed patients](http://www.rd-code.eu/wp-content/uploads/2022/02/D5.2_RDCODE_VF2021_FV.pdf), in recommendation 3 it says: 
_Additional phenotypic descriptors could be used (for instance ICD, SNOMED, **Orphanet categories**...)_

And we understand that with **Orphanet categories** they mean the Orphanet groups of diseases.
Could you clarify it?

Kind regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Thanks Marie-Cécile,

Much more clear now.

Kind regards, 

María Elena
