### ISSUE TITLE
Non-Dravet developmental and epileptic Encephalopathy type 6B

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#56]
Hello,

Please find below a request from a Swiss coder:

“We have a child with Non-Dravet developmental and epileptic Encephalopathy type 6B (DEEB6). The OMIM-Number is 619317. But we can’t find an appropriate Orphacode. The genetic mutation is in the SCN1A gene. Do you know if an Orphacode is planning?“

Let us know if you need more information.
Thank you

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, 

I have just checked and this OMIM number is present in the list of potential creations from OMIM watch we perform every month. I will review this creation and give you an update in May. 

Best, 

Julie

**Comment by OrphanetSwitzerland** [comment]
Hello,
We are reopening this issue because the gene is still not linked to the entity.
Thank you

**Comment by Mickael-Orphanet** [comment]
Dear @OrphanetSwitzerland , 

The gene has been linked. It should be visible monday. 

Best, 
Mickael
