### ISSUE TITLE
Cardiac-urogenital syndrome (gene MYRF)

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#57]
Please find below a request from a Swiss coder:

“I have a disease for which I can’t find an Orphacode: OMIM 618280 Cardiac-urogenital syndrome, Gene: MYRF. 
I think it was first described in 2018: https://www.researchgate.net/publication/339982791_The_clinical_overlap_between_cardiac-urogenital_syndrome_Meacham_syndrome_and_PAGOD_syndrome_Report_of_a_new_patient_with_cardiac-urogenital_syndrome.
 Do you know if they are already considering this disease for inclusion?"

Let us know if you need more information.
Thank you

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, 

This creation is not currently in the pipeline, but I will check if it's a potential creation. I will let you know in May. 

Best, 

Julie
