### ISSUE TITLE
Leigh syndrome - TTC19 gene

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#59]
A geneticist requests to link Leigh syndrome (ORPHA:506) to the TTC19 gene (GenID 19839), based on these publications:

https://pubmed.ncbi.nlm.nih.gov/25899669/
https://pubmed.ncbi.nlm.nih.gov/24368687/

Thank you

**Comment by MCecile-US14** [comment]
Dear @mutaz-amin, 

Can you please look into this syndrome and link the gene accordingly ?
Thank you, 
MC

**Comment by MCecile-US14** [comment]
Dear @mutaz-amin, 

Kind reminder, can you please look into this gene to be linked to the Leigh syndrome .
Thank you, 
Kind Regards
Marie-Cécile

**Comment by mutaz-amin** [comment]
Dear @OrphanetSwitzerland,

I reviewed the two publications provided by the expert, and I found that one of them (PMID: 25899669) reported one patient with Isolated complex III deficiency (ORPHA:1460) which is already aligned to the gene in Orphanet. The other publication (PMID: 24368687) indeed reported the phenotype of Leigh syndrome but in only one patient which is not considered enough evidence to link the gene in Orphanet. I hope this answers your question and please let me know if you have more

Thank you very much

Mutaz

**Comment by OrphanetSwitzerland** [comment]
Thank you Mutaz
