### ISSUE TITLE
Sifrim-Hitz-Weiss syndrome

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#62]
One of our expert center (for dental care for rare disorder patients) have a patient with mutation in gene CDH4 compatible with OMIM 617159 Sifrim-Hitz-Weiss syndrome. We therefore ask Orphanet to consider whether this syndrome should be added to Orphanet and be given an ORPHAcode.

Best regards,
Lene
Norway National Orphanet Hub

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

Thanks for the message, I will review this request in May. I can't assure you that it will be included in the nomenclature pack due to a significant number of creations in the pipeline, but I will let you know ASAP. 

Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

I am sorry, due to a huge number of requests, I didn't present this request. I will do it for the next Orphanet committee on June (the 14th). 

Thank you for your patience, 

Julie

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

We have validated the creation of this new syndrome in our database. Please find it under the ORPHAcode 653712 and named CHD4-related neurodevelopmental disorder. 

Thank you very much for your patience, 

Julie

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen,

We have validated the creation of this new syndrome in our database. Please find it under the ORPHAcode 653712 and named CHD4-related neurodevelopmental disorder.

Thank you very much for your patience,

Julie
