### ISSUE TITLE
CAKUTHED - PBX1-associated malformation syndrome

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#64]
Hello,

Here is a demand from the Kinderspital Zurich:

"We have a patient with a PBX1-associated malformation syndrome: CAKUTHED (Congenital anomalies of kidney and urinary tract syndrome with or without hearing loss, abnormal ears, or developmental delay). For CAKUTHED there is an OMIM number: 617641 but as far as I can see no Orphacode".

Please see the references: 
https://academic.oup.com/hmg/article/26/24/4849/4210002
https://journals.lww.com/jasn/Fulltext/2017/10000/Targeted_Exome_Sequencing_Identifies_PBX1_as.13.aspx
https://www.omim.org/entry/617641

Thank you

**Comment by MCecile-US14** [comment]
Dear @JTorphanet, 

When you have time can you look up this disease please et let @OrphanetSwitzerland know.
Thank you, 
Marie-Cécile

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, 

I will review this request in June. I will let you know ASAP. 

Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, 

Just to keep you informed, we have asked an expert advice to ERKnet because we have some doubts about this creation due to the high variability of the clinical picture. 

I will let you know as soon as I receive a reply. 

Best regards, 

Julie

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, 

Sorry for the delay, ERKnet experts have validated the perimeter of this disease as a new syndromic form of CAKUT and following the Orphanet committee, I have proceeded to the creation. 
Name: PBX1-related congenital anomalies of kidney and urinary tract syndrome, under ORPHAcode: 656130

It will be visible in the next 24h on our website. 

Thank you, 
Best, 

Julie
