### ISSUE TITLE
ICD-10 Mapping file

### ISSUE THREAD

**Issue by uunter98** [OD4RD/Main-Help-Desk#65]
Dear Julie and everyone who might be involved in this,
would it be possible for the nomenclature pack 2023 to include also those entities for which the mapping has not been done yet? And also have columns for active/inactive entities and classification level (to easily filter out groups)? Or to show me/us how to compare this file to the nomenclature file in excel and insert missing entities / add unwanted ones easily? I know I am not an IT genius and this request is probably embarassing, but it would help me a lot..
thxx
Ursula

**Comment by JTorphanet** [comment]
Dear @uunter98, 

I have started to discuss with the IT team to improve infos for the mapping part in the Nomenclature pack, but some upgrades are not possible or difficult to implement in the time available. However, if no solution is found for the next release, I will propose alternatives to make your work as easy as possible. 

Thank you for your patience, 
Best regards,

Julie

**Comment by JTorphanet** [comment]
Dear @uunter98, 

We have decided to upgrade some products in the next nomenclature pack (June 2023). We will propose a new ICD11 mapping file with two supplementary columns containing: the webpage link corresponding to the MMS code attributed and one column for the URI from the foundation. 

Moreover, we will generate an updated version of the Masterfile (currently, you have only the ICD10 code) with the  all ICD alignments: ORPHAcode to ICD10, ORPHAcode to ICD-11 MMS, ORPHAcode to ICD-11 foundation. 

For the other points, it's possible with the current files provided. Finally, we will organize a training in September/october to help users with the mapping part. 

Best, 

Julie
