### ISSUE TITLE
Coding of chromosomal rearrangements

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#66]
Hello,

We have a question concerning coding av ultra rare patients with complex chromosonal rearrangements. Two of our expert centers need to code a patient with a genetic composition that is very complext and most likely one of a kind in Norway, perhaps also in Europe and the world. We (the National Hub) don't have the details for this patient but have been told that the patient have one or more unbalanced translactions on automsomes. Frambu Resource Centre for Rare Disorders use the ICD-10 code Q99.8 for such patients. The other expert centre, TAKO centre - National Resource Centre for Oral Health in Rare Diagnosis, is looking into using an ORPHA group code but since groups are not described, they hesitate. The group code in question is ORPHA:263708 Complex chromosomal rearrangement.

What is Orphanet's thoughts on coding complex chromosomal rearrangements? Do you have any recommendations for the specific case mentioned above?

For some group codes it would perhaps help the professionals if there was some information on what to include, or not include, in a group code. A good example is the one mentioned above - ORPHA:263708 Complex chromosomal rearrangement. It could be very short and simple, with e.g. "Excl. ...." if there were specific conditions not to be included in a certain group code.

These questions could also be discussed in the OD4RD2 meetings if time allows.

Kind regards,
Lene

**Comment by MCecile-US14** [comment]
Dear Lene, 

Thanks a lot for your coding question on complex chromosomal rearrangements. I am currently curating different types of requests to revise the cytogenetics Nomenclature so I will also work on this demand to come back to you with an appropriate answer and add it to the Wiki page with more general feedebacks with the use of ORPHAcode group such as ORPHA:263708.

And yes this is definitely the type of topics that can be discuss within the "WP4 - OD4RD2 - coding and nomenclature open sessions' (need to be different from the WP4 monthly meeting themselves that are already timed and packed wtih all the NH's presentations.

Kind Regards
Marie-Cécile

**Comment by Orphanet-AysegulSenol** [comment]
Dear Lene, 

I just wanted to inform you that we started to work on the definition for ORPHA:263708. We aim to publish it in couple of months. It could take bit longer depending on when the medical validation could be performed. We will keep you posted. 

Kind regards, 

Aysegul
