### ISSUE TITLE
ORPHA:227510  Multiple system atrophy, cerebellar type - wrong ICD-10

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#67]
Dear all,

Regarding "Multiple system atrophy", there is a discrepancy between the ICD-10 assigned to the disease and the subtypes.

ORPHA:102   (Disorder)   Multiple system atrophy > ICD-10: G23.2  G23.3
ORPHA:227510   (Subtype of disorder)   Multiple system atrophy, cerebellar type > ICD-10: **G90.3**
ORPHA:98933   (Subtype of disorder)   Multiple system atrophy, parkinsonian type > ICD-10: G23.2

As you can see on the WHO website, the ICD-10 code for cerebellar type is **G23.3**, instead of G90.3, which doesn't exist in the latest version of the classification.
https://icd.who.int/browse10/2019/en#/G23.3
Furthermore, in Orphanet, the disorder has the codes of its subtypes attributed, with the correct code for the cerebella type.

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

Indeed, there is a misalignement. I will check tomorrow and perform the double validation with the scientific director. I will let you know about the changes. 

Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES , 

I confirm that ORPHAcode: 227510 Multiple system atrophy, cerebellar type must be linked to G23.3 as an exact match. 

Thank you for your contribution, 

Best, 

Julie
