### ISSUE TITLE
New neurodevelopmental disorder related to loss-of-function variants in SRRM2

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#74]
Dear all,

We have received a message from a patients association dealing with a neurodevelopmental disorder related to loss-of-function variants in SRRM2.
They are questioning the reason why the disease is not included in Orphanet.
Please refer to the following publication:
https://pubmed.ncbi.nlm.nih.gov/35567594/ 

Thank you in advance and kind regards,

María Elena

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 ,

Thank you for handling this request so quickly.
We will translate the name of the disorder into Spanish and inform the association that requested its creation.

Kind regards,

María Elena

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 ,

After reviewing the created disease, I have seen that you have not linked the gene SRRM2.
Can you link it?
And are you going to create a synonym that reflects the relationship with this gene?

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Thank you for your message.
After each ORPHAcode creation the gene-phenotype relationship is checked and will be apply by the manager in charge of, it is two different internal workflows, genes are applied secondary to the creation  ;-)
Regarding the synonym, as you know in the Orphanet Nomenclature rules and procedure, we consider all the synonyms that are exact concept as perimeter of diseases and are commonly used/published (by languages) to best represent the current knowledge.
In this case (very recent genotype-phenotype correlation), so far, there is only two publications mentioning the described syndrome as distinct and the 'gene name' does not exist (no phenotype MIM#) 
Once the gene is linked it will appear in the search also so the syndrome will be searchable anyway.

Kind Regards, 
Marie-Cécile
