### ISSUE TITLE
Mitochondrial disease, ECHS1 mutations

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#77]
Hello,

Please find below a comment from a Swiss coder concerning a mitochondrial disease: 

"I have a patient with a Mitochondrial Short-Chain Enoyl-CoA Hydratase 1 Deficiency (ECHS1-Mutation, OMIM 616277). In Orphanet the search over the OMIM number brings me to Leigh syndrome with leukodystrophy (ORPHA:255241) which is now moved to Leigh syndrome (ORPHA:506). The doctor in charge of supervising the coding thinks “it is a mitochondrial disease “Leigh-like”, but not Leigh syndrome”. Could you take a look at this issue?"

Thanks

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Thank you for your message. 
As usual, could you provide us with some reference and context for 'mitochondrial disease Leigh-like' (PMID; genotype-phenotype association; clinical case report; patient case etc...) mentioned by the medical doctor to facilitate the evaluation of the request ? ECHS1 gene exists in Orphanet but is not linked yet to any rare diseases.

Thank you 
Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @Orphanet-AysegulSenol, 

As discussed today, could you please follow up this issue mentionning 'Mitochondrial Short-Chain Enoyl-CoA Hydratase 1 Deficiency' (ECHS1 mutations) as you are currently revising the group of rare metabolic disorders with MetabERN and let @OrphanetSwitzerland what is the final decision for this entity.

Thank you, 
Kind Regards, 
Marie-Cécile

**Comment by Orphanet-AysegulSenol** [comment]
Dear @OrphanetSwitzerland,

I just wanted to update you that I am currently working on the creation of entity "Mitochondrial Short-Chain Enoyl-CoA Hydratase 1 Deficiency" (as you have also mentioned that Leigh syndrome that you are now re-directed is not a synonyme of this entity). I will update you once the creation is officially confirmed. 

Best regards,

Aysegul

**Comment by Orphanet-AysegulSenol** [comment]
Dear @OrphanetSwitzerland,

As mentioned previously, the entity "Mitochondrial short-chain enoyl-CoA hydratase 1 deficiency" is now created (Orpha: 653880).

Best regards, 

Aysegul
