### ISSUE TITLE
Definition of the term "familial" ORPHA:79147

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#78]
Hello,

Please find below a doubt we received concerning the use of the term *familial* in the name of a disease.

“I have a patient with a “reactive perforating collagenosis”. The patient is over 80 years old. Histology confirms the findings, but nothing is mentioned about a positive family history and no genetic test was performed. The name of the disease contains “familial”, which makes me unsure if I can apply the code. What is the meaning of “familial” in this context?”

In the “Procedural document: Rare disease nomenclature in English”, there is a section dedicated to “Words referring to transmission or acquisition” (page 11), but I could not find a specific definition for familial. 

Thanks

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 
Thank you for your request. We do have a lot of rare diseases registered as 'familial' (to be opposed to non familial/sporadic for instance) where the genetics as not always been identified yet (transmission mode and linked genes)
In general, if in the same group of diseases there is no sporadic/acquired forms of the disease/clinical sign described (e.g. reactive perforative collagenosis) it means maybe this disease does exist but could be not rare so is not represented in Orphanet.

In this sense, if the patient has not been genetically tested and no cases have been found in the family history nor identified, ORPHA:79147 should not been used to code this patient.
In this case, you can consult the Orphanet classification of rare skin diseases: 

>Dermis elastic tissue disorder [Group of disorders - Category] ORPHA:79378
	>'Genetic dermis elastic tissue disorder' [Group of disorders - Category] ORPHA:228215
		>> including  **'Familial reactive perforating collagenosis' [Disorder - Disease] ORPHA:79147**
	>'Acquired dermis elastic tissue disorder' [Group of disorders - Category] ORPHA:228218
		>'Acquired dermis elastic tissue disorder with decreased elastic tissue' [Group of disorders - Category]ORPHA:228221
		>'Acquired dermis elastic tissue disorder with increased elastic tissue' [Group of disorders - Category] ORPHA:228224

An acquired form of 'reactive perforating collagenosis' (RPC) is not present and after some research it does not seems rare to be included in Orphanet according to PMID:32481426 (2020) and PMID:27472707 (2016) "there are 2 types of RPC, acquired RPC (ARPC) and inherited RPC, while the latter is considered extremely rare." "RPC is a rare form of transepithelial elimination associated with various internal diseases and malignant neoplasms."

Hope this clarify the coding issue, regarding the term 'familial' I take note to include a sentence about it in the procedural document.
Kind regards, 
Marie-Cécile
