### ISSUE TITLE
ORPHA:306511 Autosomal recessive spastic paraplegia type 48 - name/inheritance or classification 

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#81]
Dear all,

As for SPG48, according to the name and the identification card of the disease, it seems that it is "autosomal recessive".
https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=21221 
But it is classified under the groups of disorders:
Pure or complex autosomal recessive spastic paraplegia ORPHA:320346
Pure or complex autosomal dominant spastic paraplegia ORPHA:320342

Please review the mode of inheritance of this disease and correct the name/inheritance if necessary, or the groups to which it is assigned.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear Marta, 

Same as GitHub #80 could you please review SPG48 OPRHA:306511 according to the suggestions made and see if if some misclassification or inheritance mode have been wrongly attributed.
Thank you, 
Marie-Cécile

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @Orphanet-ES,

Thank you very much for your comment. We will correct the entry ORPHA:306511.

Best regards,

Marta
