### ISSUE TITLE
ORPHA:631068  Autosomal dominant spastic paraplegia type 80 - ICD-10

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#84]
Dear all,

Please, review the assigned ICD-10 code: "G82.1 Spastic paraplegia"

Since the inheritance is autosomal dominant, shouldn't it be assigned the code "G11.4 Hereditary spastic paraplegia"?

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

Thank you for your message, indeed the right code is G11.4. I have also detected a misalignment with the ICD11 code. Modifications done. 

Thanks for your contribution, 

Best regards, 
Julie
