### ISSUE TITLE
ORPHA:280763  Severe intellectual disability and progressive spastic paraplegia - ICD-10

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#85]
Dear all, 

Please, review the assigned ICD-10 code: "G82.1 Spastic paraplegia".

Since the inheritance is autosomal recessive, shouldn't it be assigned the code "G11.4 Hereditary spastic paraplegia"?

Kind regards,

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

Thanks for the suggestion, it's true the appropriate code is G11.4. Modification done. 

Best regards, 

Julie
