### ISSUE TITLE
Retinitis pigmentosa ORPHA:791

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#88]
Dear Helpdesk

A clinician at the Department of ophthalmology, Oslo University Hospital, was surprised that there is
only one ORPHAcode for Retinitis Pigmentosa (ORPHA:791, disorder). She requests subtypes (based
on clinical presentation, not genetics only).

Are there any ongoing or planned initiatives to update the nomenclature when it comes to Retinitis
Pigmentosa? If not, I will ask the clinician to provide specific suggestions with documentation.

Thank you!

Kind regards,
Lene

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

No revision has been planned at the moment, but we are interested in having documentation. I'm starting a collaboration in September with ERN eye for other disorders, so it would be interesting to do this in parallel. 

Best regards, 

Julie

**Comment by LeneMartinsen** [comment]
Dear @JTorphanet 

Thanks for the quick reply.

Great that there will be a collaboration with ERN eye.
We will then ask the clinicians for documentation for subtypes of Retinitis pigmentosa. Right now we are in the midle of summer vacation in Norway so it will probably come in August. Will keep you posted!

Kind regards,
Lene
