### ISSUE TITLE
Sucac Syndrome

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#90]
This is not an "issue".  Just wanted to let you know that there is another registry in USA for Susac syndrome: https://novel.utah.edu/about/rare-disease/susac-syndrome 

Also, you can link to the NORD report (English and Spanish): https://rarediseases.org/rare-diseases/susacs-syndrome/

**Comment by MCecile-US14** [comment]
Dear @galyea123, 

Thank you for your request.
I forwarded the request to reference another registry in USA for Susac syndrome to the Orphanet data manager in charge. She will evaluate and update the list accordingly.

Regarding the NORD report, currently we reference GARD link whom is using Orphanet data with our creative licence (cc by) in our 'others websites' in the additional informations section. https://www.orpha.net/consor4.01/www/cgi-bin/Disease_Search_Simple.php?lng=EN&type_list=Other_Websites&LnkId=8614&Typ=Pat&from=rightMenu

We are also interacting with them at the moment about future agreement, we are taking note of your suggestions.
For now, Orphanet' policy do not systematically add external disease report (as PDF content) for each disease, outside of european references. 

Kind Regards, 
Orphanet coord. team
