### ISSUE TITLE
Pulmonary Artery Sling

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#93]
Hello,

Request from a Swiss coder:

A patient presents a malformation not listed in Orphanet: “Pulmonary Artery Sling” or “Pulmonary Sling” (https://link.springer.com/article/10.1007/BF01972965).

There is an HPO code for this malformation (HP:0004961) associated to Mowat-Wilson syndrome but the patient presents it isolated.

Let us know if you consider adding it to the nomenclature and if you need bibliographic support.
Thank you

**Comment by MCecile-US14** [comment]
Dear @JTorphanet, 

When you have time, can you please take a look at this request and see if up for creation?

Thank you!
Marie-Cécile

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, 

Just to let you know, I will review this request in October and I will inform you ASAP. 
Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, 

Just to inform you that the Orphanet committee has validated the creation of this entity: "Isolated pulmonary artery sling" under ORPHAcode: 658574. 

Best regards, 

Julie

**Comment by OrphanetSwitzerland** [comment]
Thank you!
