### ISSUE TITLE
NESCAV syndrome

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#94]
Hello,

Here is a request from a coder at the Inselpistal in Bern:

A patient presents genetic results (pathogenic variant in the KIF-1A gene) and a clinical picture compatible with NESCAV syndrome (OMIM 614255).

In Orphanet, this OMIM number is aligned with ORPHA:178469 - Autosomal dominant non-syndromic intellectual disability.

The patient has Hereditary sensory neuropathy type II (ORPHA:970) and spastic paraplegia type 30 (ORPHA:101010). Epilepsy and developmental delay are also present.

Would you consider the creation of NESCAV syndrome? (The different ORPHAcodes mentioned do not seem appropriate to code this patient).
Reference: PMID: 32096284

Thank you

**Comment by MCecile-US14** [comment]
Dear @Orphanet-MartaFructuoso, 

Kind Reminder, could you please update @OrphanetSwitzerland about the decision taken by Orphanet scientific and medical committee regarding NESCAV syndrome, upon your return 

Thank you, 
Marie-Cécile

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @OrphanetSwitzerland,

Based on the medical and scientific literature, the Orphanet committee has validated the creation of the " NESCAV syndrome" under "ORPHA:662367". 
The clinical features, considered homogenous and described in at least two individuals for the time being, include: moderate to severe intellectual disability, language and motor delay, hypotonia, spastic paraparesis, hyperreflexia, postnatal microcephaly, and peripheral neuropathy. A disease-causing gene, KIF1A has been linked to this entity. Other resources will be associated in the future.
Best regards,
Marta

**Comment by OrphanetSwitzerland** [comment]
Thank you!
