### ISSUE TITLE
E-mail from IT developer i Norway

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#95]
Hi Marc,

Just wanted to reach out because an IT developer i Norway has sent you an e-mail, and also contacted Orphadata through the website. She is responsible for developing a new solution for ORPHAcodes in the electronic patient record at Oslo Univ Hospital. This is great news for us, because this is a step towards a solution that can be used by other health regions as well.

Her name: Gerd Elise Martinsen. E-mail: gem@dips.no

If you could get back to her asap that would be fantastic! :)

Btw, hope you've had a great summer!

All the best,
Lene

**Comment by Orphanet** [comment]
Dear @LeneMartinsen APIkey code sent by mail to Gerd Elise Martinsen

Best regards,
