### ISSUE TITLE
New syndrome: Parenti-Mignot neurodevelopmental syndrome (PMNDS)

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#98]
Dear all, 

We would like to propose the inclusion in Orphanet of a new syndrome, at the request of the parents of a recently diagnosed patient in Spain:
 # 619873 PARENTI-MIGNOT NEURODEVELOPMENTAL SYNDROME; PMNDS
https://omim.org/entry/619873

This syndrome was first described in 2021, so there seems to be only one publication about it, but it affects at least 16 patients, and also the newly diagnosed Spanish patient.
As there is only one publication, please let me know if you need more information to include this syndrome in Orphanet.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Hi @JTorphanet, 

Can you evaluate this request?
Thank you, 
Marie-Cécile

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

I took a look at your request and the gene is already linked to the ORPHAcode: 528084 Non-specific syndromic intellectual disability. However, I will check the publication and define the clinical picture to determine if this syndrome falls within the scope of this ORPHAcode or requires a new one. 

This request will be reviewed by the committee in october and I will let you know ASAP. 

Best, 

Julie

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 , 

Is there any news about this issue?

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

Due to a huge number of requests for the last Orphanet committee, I did not have enough time to present this one. We will discuss about it in December. Sorry for the delay. 

Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

We have reviewed this request and for the moment, we can not validate the creation. As you raised, there is only one publication with 16 individuals and a strong overlap with an entity we already have: ORPHAcode 1606 "1p36 deletion syndrome". CHD5 gene is located into a critical region and we need to wait further publications to delimit a clear clinical perimeter. 

The CHD5 gene is already registered in the database and linked to ORPHA 528084 Non-specific syndromic ID. We will add the OMIM number 619873 as BTNT relationship. 

I wish you a very happy festive season!
Best, 

Julie

**Comment by Orphanet-ES** [comment]
Dear @JTorphanet ,

Thanks for your anwer.

I will forward your comments to those who contacted us.

Reviewing the criteria for creating a new ORPHA, I believe that the number of publications is not considered as much as the number of unrelated cases. 
In any case, as this syndrome has only recently been described, it will be better to wait for more information.

I wish you a very happye festive season!
Kind regards, 

María Elena
